version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Hoanglong2502
      - POSTGRES_DB=pharmago
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:Hoanglong2502@postgres:5432/pharmago?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "postgres:5432" ]
    command: [ "/app/main" ]