ALTER TABLE companies ALTER COLUMN owner SET NOT NULL;
ALTER TABLE companies ADD CONSTRAINT unique_code UNIQUE (code);
ALTER TABLE address ALTER COLUMN lat TYPE DOUBLE PRECISION;
ALTER TABLE address ALTER COLUMN lng TYPE DOUBLE PRECISION;