// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: account_type.sql

package db

import (
	"context"
	"database/sql"
)

const getAccountType = `-- name: GetAccountType :one
SELECT id, code, title from account_type
WHERE id = $1
    OR code = $2
LIMIT 1
`

type GetAccountTypeParams struct {
	ID   sql.NullInt32  `json:"id"`
	Code sql.NullString `json:"code"`
}

func (q *Queries) GetAccountType(ctx context.Context, arg GetAccountTypeParams) (AccountType, error) {
	row := q.db.QueryRowContext(ctx, getAccountType, arg.ID, arg.Code)
	var i AccountType
	err := row.Scan(&i.ID, &i.Code, &i.Title)
	return i, err
}
