// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: customer.sql

package db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    full_name, code, company, address, email, phone ,license, birthday, user_updated, user_created
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, full_name, code, company, address, email, phone, license, birthday, user_created, user_updated, updated_at, created_at
`

type CreateCustomerParams struct {
	FullName    string         `json:"full_name"`
	Code        string         `json:"code"`
	Company     int32          `json:"company"`
	Address     sql.NullInt32  `json:"address"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	License     sql.NullString `json:"license"`
	Birthday    sql.NullTime   `json:"birthday"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	UserCreated int32          `json:"user_created"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.FullName,
		arg.Code,
		arg.Company,
		arg.Address,
		arg.Email,
		arg.Phone,
		arg.License,
		arg.Birthday,
		arg.UserUpdated,
		arg.UserCreated,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Code,
		&i.Company,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.License,
		&i.Birthday,
		&i.UserCreated,
		&i.UserUpdated,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, full_name, code, company, address, email, phone, license, birthday, user_created, user_updated, updated_at, created_at FROM customers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Code,
		&i.Company,
		&i.Address,
		&i.Email,
		&i.Phone,
		&i.License,
		&i.Birthday,
		&i.UserCreated,
		&i.UserUpdated,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomer = `-- name: ListCustomer :many
SELECT id, full_name, code, company, address, email, phone, license, birthday, user_created, user_updated, updated_at, created_at FROM customers
WHERE company = $1::int
AND (
    full_name ILIKE '%' || COALESCE($2::varchar, '') || '%' OR
    code ILIKE '%' || COALESCE($2::varchar, '') || '%'
)
ORDER BY -id
LIMIT COALESCE($4::int, 10)
OFFSET (COALESCE($3::int, 1) - 1) * COALESCE($4::int, 10)
`

type ListCustomerParams struct {
	Company int32          `json:"company"`
	Search  sql.NullString `json:"search"`
	Page    sql.NullInt32  `json:"page"`
	Limit   sql.NullInt32  `json:"limit"`
}

func (q *Queries) ListCustomer(ctx context.Context, arg ListCustomerParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomer,
		arg.Company,
		arg.Search,
		arg.Page,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Code,
			&i.Company,
			&i.Address,
			&i.Email,
			&i.Phone,
			&i.License,
			&i.Birthday,
			&i.UserCreated,
			&i.UserUpdated,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
