// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: media.sql

package db

import (
	"context"
)

const getMedia = `-- name: GetMedia :one
SELECT id, media_url FROM medias
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (Media, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Media
	err := row.Scan(&i.ID, &i.MediaUrl)
	return i, err
}
