// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Gender string

const (
	GenderNam Gender = "nam"
	GenderN   Gender = "nữ"
	GenderKhc Gender = "khác"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type MedicalRecordLinkType string

const (
	MedicalRecordLinkTypeTest       MedicalRecordLinkType = "test"
	MedicalRecordLinkTypePatient    MedicalRecordLinkType = "patient"
	MedicalRecordLinkTypeDiagnostic MedicalRecordLinkType = "diagnostic"
)

func (e *MedicalRecordLinkType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MedicalRecordLinkType(s)
	case string:
		*e = MedicalRecordLinkType(s)
	default:
		return fmt.Errorf("unsupported scan type for MedicalRecordLinkType: %T", src)
	}
	return nil
}

type NullMedicalRecordLinkType struct {
	MedicalRecordLinkType MedicalRecordLinkType `json:"medical_record_link_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if MedicalRecordLinkType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMedicalRecordLinkType) Scan(value interface{}) error {
	if value == nil {
		ns.MedicalRecordLinkType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MedicalRecordLinkType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMedicalRecordLinkType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MedicalRecordLinkType), nil
}

type Account struct {
	ID                int32          `json:"id"`
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	FullName          string         `json:"full_name"`
	Email             string         `json:"email"`
	Type              int32          `json:"type"`
	IsVerify          bool           `json:"is_verify"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	Role              sql.NullInt32  `json:"role"`
	Gender            NullGender     `json:"gender"`
	Licence           sql.NullString `json:"licence"`
	Dob               sql.NullTime   `json:"dob"`
	Address           sql.NullInt32  `json:"address"`
}

type AccountCompany struct {
	ID      int32 `json:"id"`
	Account int32 `json:"account"`
	Company int32 `json:"company"`
}

type AccountMedium struct {
	ID      int32 `json:"id"`
	Account int32 `json:"account"`
	Media   int32 `json:"media"`
}

type AccountType struct {
	ID    int32  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type Address struct {
	ID          int32          `json:"id"`
	Lat         float64        `json:"lat"`
	Lng         float64        `json:"lng"`
	Province    sql.NullString `json:"province"`
	District    sql.NullString `json:"district"`
	Ward        sql.NullString `json:"ward"`
	Title       string         `json:"title"`
	UserCreated int32          `json:"user_created"`
	CreatedAt   time.Time      `json:"created_at"`
}

type AdministrativeRegion struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	NameEn     string `json:"name_en"`
	CodeName   string `json:"code_name"`
	CodeNameEn string `json:"code_name_en"`
}

type AdministrativeUnit struct {
	ID          int32  `json:"id"`
	FullName    string `json:"full_name"`
	FullNameEn  string `json:"full_name_en"`
	ShortName   string `json:"short_name"`
	ShortNameEn string `json:"short_name_en"`
	CodeName    string `json:"code_name"`
	CodeNameEn  string `json:"code_name_en"`
}

type App struct {
	ID     int32          `json:"id"`
	Title  string         `json:"title"`
	Code   string         `json:"code"`
	Parent sql.NullString `json:"parent"`
	Level  sql.NullInt32  `json:"level"`
}

type AppointmentSchedule struct {
	ID       int32         `json:"id"`
	Uuid     uuid.UUID     `json:"uuid"`
	Code     string        `json:"code"`
	Customer sql.NullInt32 `json:"customer"`
	Company  sql.NullInt32 `json:"company"`
	Doctor   sql.NullInt32 `json:"doctor"`
	// Triệu chứng bệnh
	Symptoms sql.NullString `json:"symptoms"`
	// Chuẩn đoán bệnh
	Diagnostic sql.NullString `json:"diagnostic"`
	QrCodeUrl  sql.NullString `json:"qr_code_url"`
	// true: Đã xong, false: Chưa diễn ra
	IsDone      bool          `json:"is_done"`
	MeetingAt   time.Time     `json:"meeting_at"`
	UserCreated int32         `json:"user_created"`
	UserUpdated sql.NullInt32 `json:"user_updated"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type AppointmentScheduleDrug struct {
	ID       int32          `json:"id"`
	AsUuid   uuid.UUID      `json:"as_uuid"`
	Variant  sql.NullInt32  `json:"variant"`
	LieuDung sql.NullString `json:"lieu_dung"`
	Quantity int32          `json:"quantity"`
}

type AppointmentScheduleService struct {
	ID           int32         `json:"id"`
	AsUuid       uuid.UUID     `json:"as_uuid"`
	Service      sql.NullInt32 `json:"service"`
	OrderService sql.NullInt32 `json:"order_service"`
}

type AppointmentScheduleUrl struct {
	ID      int32          `json:"id"`
	AsUuid  uuid.UUID      `json:"as_uuid"`
	Url     sql.NullString `json:"url"`
	NameDoc sql.NullString `json:"name_doc"`
}

type Classify struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type Company struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	TaxCode     sql.NullString `json:"tax_code"`
	Phone       sql.NullString `json:"phone"`
	Description sql.NullString `json:"description"`
	Address     sql.NullInt32  `json:"address"`
	OaID        sql.NullString `json:"oa_id"`
	CreatedAt   time.Time      `json:"created_at"`
	Owner       int32          `json:"owner"`
	Type        string         `json:"type"`
	TimeOpen    sql.NullTime   `json:"time_open"`
	TimeClose   sql.NullTime   `json:"time_close"`
}

type CompanyPharma struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	Code              sql.NullString `json:"code"`
	Country           sql.NullString `json:"country"`
	Address           sql.NullString `json:"address"`
	CompanyPharmaType sql.NullString `json:"company_pharma_type"`
	CreatedAt         time.Time      `json:"created_at"`
}

type CompanyPharmaType struct {
	ID    int32  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type CompanyType struct {
	//
	// 💸 1 = CLINIC,
	// ✔️ 2 = DRUGSTORE
	//
	Code  string `json:"code"`
	Title string `json:"title"`
}

type Consignment struct {
	ID          int32         `json:"id"`
	Code        string        `json:"code"`
	Quantity    int32         `json:"quantity"`
	Inventory   int32         `json:"inventory"`
	Ticket      sql.NullInt32 `json:"ticket"`
	ExpiredAt   time.Time     `json:"expired_at"`
	ProductedAt time.Time     `json:"producted_at"`
	IsAvailable bool          `json:"is_available"`
	UserCreated sql.NullInt32 `json:"user_created"`
	UserUpdated sql.NullInt32 `json:"user_updated"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	CreatedAt   time.Time     `json:"created_at"`
	Variant     sql.NullInt32 `json:"variant"`
}

type ConsignmentLog struct {
	ID           int32         `json:"id"`
	Consignment  int32         `json:"consignment"`
	Inventory    int32         `json:"inventory"`
	AmountChange int32         `json:"amount_change"`
	UserCreated  sql.NullInt32 `json:"user_created"`
	CreatedAt    time.Time     `json:"created_at"`
}

type Customer struct {
	ID          int32          `json:"id"`
	FullName    string         `json:"full_name"`
	Code        string         `json:"code"`
	Company     int32          `json:"company"`
	Address     sql.NullInt32  `json:"address"`
	Email       sql.NullString `json:"email"`
	Phone       sql.NullString `json:"phone"`
	License     sql.NullString `json:"license"`
	Birthday    sql.NullTime   `json:"birthday"`
	UserCreated int32          `json:"user_created"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
	Group       sql.NullInt32  `json:"group"`
	// Chức danh
	Title          sql.NullString `json:"title"`
	LicenseDate    sql.NullTime   `json:"license_date"`
	ContactName    sql.NullString `json:"contact_name"`
	ContactTitle   sql.NullString `json:"contact_title"`
	ContactPhone   sql.NullString `json:"contact_phone"`
	ContactEmail   sql.NullString `json:"contact_email"`
	ContactAddress sql.NullInt32  `json:"contact_address"`
	AccountNumber  sql.NullString `json:"account_number"`
	BankName       sql.NullString `json:"bank_name"`
	BankBranch     sql.NullString `json:"bank_branch"`
	IssuedBy       sql.NullString `json:"issued_by"`
	Gender         NullGender     `json:"gender"`
}

type CustomerGroup struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Company     int32          `json:"company"`
	Note        sql.NullString `json:"note"`
	UserCreated int32          `json:"user_created"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type DebtNote struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Title       sql.NullString `json:"title"`
	Entity      string         `json:"entity"`
	Money       float64        `json:"money"`
	Paymented   float64        `json:"paymented"`
	Note        sql.NullString `json:"note"`
	Type        string         `json:"type"`
	Status      string         `json:"status"`
	Company     int32          `json:"company"`
	UserCreated int32          `json:"user_created"`
	Exprise     time.Time      `json:"exprise"`
	DabtNoteAt  sql.NullTime   `json:"dabt_note_at"`
}

type DebtNoteStatus struct {
	Code  string         `json:"code"`
	Title sql.NullString `json:"title"`
}

type DebtNoteType struct {
	Code  string         `json:"code"`
	Title sql.NullString `json:"title"`
}

type DebtRepayment struct {
	ID          int32        `json:"id"`
	Code        string       `json:"code"`
	Money       float64      `json:"money"`
	CreatedAt   sql.NullTime `json:"created_at"`
	Debt        int32        `json:"debt"`
	UserCreated int32        `json:"user_created"`
}

type District struct {
	Code                 string         `json:"code"`
	Name                 string         `json:"name"`
	NameEn               string         `json:"name_en"`
	FullName             string         `json:"full_name"`
	FullNameEn           string         `json:"full_name_en"`
	CodeName             string         `json:"code_name"`
	ProvinceCode         sql.NullString `json:"province_code"`
	AdministrativeUnitID sql.NullInt32  `json:"administrative_unit_id"`
}

type Ingredient struct {
	ID      int32   `json:"id"`
	Name    string  `json:"name"`
	Weight  float64 `json:"weight"`
	Unit    string  `json:"unit"`
	Product int32   `json:"product"`
}

type Media struct {
	ID       int32  `json:"id"`
	MediaUrl string `json:"media_url"`
}

type MedicalRecord struct {
	ID       int32           `json:"id"`
	Code     string          `json:"code"`
	Customer int32           `json:"customer"`
	Weight   sql.NullFloat64 `json:"weight"`
	Long     sql.NullFloat64 `json:"long"`
	// Triệu chứng
	Symptom string `json:"symptom"`
	// Chuẩn đoán
	Diagnostic string `json:"diagnostic"`
	// Kết luận
	Result        string         `json:"result"`
	Doctor        sql.NullInt32  `json:"doctor"`
	ReExamination int32          `json:"re_examination"`
	Note          sql.NullString `json:"note"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	UserCreated   sql.NullInt32  `json:"user_created"`
	UserUpdated   sql.NullInt32  `json:"user_updated"`
}

type MedicalRecordLink struct {
	ID                  int32                 `json:"id"`
	Uuid                uuid.UUID             `json:"uuid"`
	Type                MedicalRecordLinkType `json:"type"`
	Title               sql.NullString        `json:"title"`
	Url                 string                `json:"url"`
	Customer            sql.NullInt32         `json:"customer"`
	AppointmentSchedule uuid.NullUUID         `json:"appointment_schedule"`
	UserCreated         sql.NullInt32         `json:"user_created"`
	CreatedAt           time.Time             `json:"created_at"`
}

type MedicalRecordVariant struct {
	ID            int32 `json:"id"`
	MedicalRecord int32 `json:"medical_record"`
	Variant       int32 `json:"variant"`
}

type NotiType struct {
	Code string `json:"code"`
}

type Notification struct {
	ID      int32  `json:"id"`
	Type    string `json:"type"`
	Topic   string `json:"topic"`
	Title   string `json:"title"`
	Content string `json:"content"`
	IsRead  bool   `json:"is_read"`
	// save code entity
	Data      sql.NullString `json:"data"`
	Company   sql.NullInt32  `json:"company"`
	CreatedAt time.Time      `json:"created_at"`
}

type Order struct {
	ID           int32          `json:"id"`
	Code         string         `json:"code"`
	TotalPrice   float64        `json:"total_price"`
	Description  sql.NullString `json:"description"`
	Vat          float64        `json:"vat"`
	Discount     string         `json:"discount"`
	ServicePrice float64        `json:"service_price"`
	MustPaid     float64        `json:"must_paid"`
	Customer     sql.NullInt32  `json:"customer"`
	Address      sql.NullInt32  `json:"address"`
	Status       sql.NullString `json:"status"`
	Type         sql.NullString `json:"type"`
	Ticket       sql.NullInt32  `json:"ticket"`
	Qr           sql.NullInt32  `json:"qr"`
	Company      int32          `json:"company"`
	Payment      int32          `json:"payment"`
	UserCreated  sql.NullInt32  `json:"user_created"`
	UserUpdated  sql.NullInt32  `json:"user_updated"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type OrderItem struct {
	ID             int32         `json:"id"`
	Order          int32         `json:"order"`
	Variant        int32         `json:"variant"`
	Value          int32         `json:"value"`
	TotalPrice     float64       `json:"total_price"`
	Consignment    sql.NullInt32 `json:"consignment"`
	ConsignmentLog sql.NullInt32 `json:"consignment_log"`
}

type OrderStatus struct {
	ID    int32  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type OrderType struct {
	ID    int32  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type Payment struct {
	ID       int32   `json:"id"`
	Code     string  `json:"code"`
	MustPaid float64 `json:"must_paid"`
	HadPaid  float64 `json:"had_paid"`
	NeedPay  float64 `json:"need_pay"`
}

type PaymentItem struct {
	ID        int32          `json:"id"`
	Type      string         `json:"type"`
	Value     float64        `json:"value"`
	IsPaid    bool           `json:"is_paid"`
	Payment   int32          `json:"payment"`
	ExtraNote sql.NullString `json:"extra_note"`
}

type PaymentItemType struct {
	ID    int32  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type PreparationType struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Company     sql.NullInt32  `json:"company"`
	UserCreated sql.NullInt32  `json:"user_created"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Description sql.NullString `json:"description"`
}

type PriceList struct {
	ID          int32         `json:"id"`
	VariantCode string        `json:"variant_code"`
	VariantName string        `json:"variant_name"`
	PriceImport float64       `json:"price_import"`
	PriceSell   float64       `json:"price_sell"`
	Unit        int32         `json:"unit"`
	UserCreated int32         `json:"user_created"`
	UserUpdated sql.NullInt32 `json:"user_updated"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	CreatedAt   time.Time     `json:"created_at"`
}

type PriceListLog struct {
	ID             int32         `json:"id"`
	OldPriceImport float64       `json:"old_price_import"`
	NewPriceImport float64       `json:"new_price_import"`
	OldPriceSell   float64       `json:"old_price_sell"`
	NewPriceSell   float64       `json:"new_price_sell"`
	PriceList      int32         `json:"price_list"`
	UserUpdated    sql.NullInt32 `json:"user_updated"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type Product struct {
	ID              int32          `json:"id"`
	Name            string         `json:"name"`
	Code            string         `json:"code"`
	ProductCategory sql.NullInt32  `json:"product_category"`
	Type            sql.NullInt32  `json:"type"`
	Brand           sql.NullInt32  `json:"brand"`
	Unit            int32          `json:"unit"`
	TaDuoc          sql.NullString `json:"ta_duoc"`
	NongDo          sql.NullString `json:"nong_do"`
	LieuDung        sql.NullString `json:"lieu_dung"`
	ChiDinh         sql.NullString `json:"chi_dinh"`
	ChongChiDinh    sql.NullString `json:"chong_chi_dinh"`
	CongDung        sql.NullString `json:"cong_dung"`
	TacDungPhu      sql.NullString `json:"tac_dung_phu"`
	ThanTrong       sql.NullString `json:"than_trong"`
	TuongTac        sql.NullString `json:"tuong_tac"`
	BaoQuan         sql.NullString `json:"bao_quan"`
	DongGoi         sql.NullString `json:"dong_goi"`
	PhanLoai        sql.NullString `json:"phan_loai"`
	DangBaoChe      sql.NullString `json:"dang_bao_che"`
	TieuChuanSx     sql.NullString `json:"tieu_chuan_sx"`
	CongTySx        sql.NullInt32  `json:"cong_ty_sx"`
	CongTyDk        sql.NullInt32  `json:"cong_ty_dk"`
	Active          bool           `json:"active"`
	Company         int32          `json:"company"`
	UserCreated     int32          `json:"user_created"`
	UserUpdated     sql.NullInt32  `json:"user_updated"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ProductBrand struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	UserCreated int32          `json:"user_created"`
	CreatedAt   time.Time      `json:"created_at"`
	Company     int32          `json:"company"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Description sql.NullString `json:"description"`
}

type ProductCategory struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	UserCreated int32          `json:"user_created"`
	CreatedAt   time.Time      `json:"created_at"`
	Company     int32          `json:"company"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Description sql.NullString `json:"description"`
}

type ProductMedium struct {
	ID      int32 `json:"id"`
	Product int32 `json:"product"`
	Media   int32 `json:"media"`
}

type ProductType struct {
	ID          int32     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	UserCreated int32     `json:"user_created"`
	CreatedAt   time.Time `json:"created_at"`
	Company     int32     `json:"company"`
}

type ProductionStandard struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Company     sql.NullInt32  `json:"company"`
	UserCreated sql.NullInt32  `json:"user_created"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Description sql.NullString `json:"description"`
}

type ProductsBank struct {
	ID           int32          `json:"id"`
	Name         string         `json:"name"`
	Code         string         `json:"code"`
	TaDuoc       sql.NullString `json:"ta_duoc"`
	NongDo       sql.NullString `json:"nong_do"`
	LieuDung     string         `json:"lieu_dung"`
	ChiDinh      string         `json:"chi_dinh"`
	ChongChiDinh sql.NullString `json:"chong_chi_dinh"`
	CongDung     string         `json:"cong_dung"`
	TacDungPhu   string         `json:"tac_dung_phu"`
	ThanTrong    string         `json:"than_trong"`
	TuongTac     sql.NullString `json:"tuong_tac"`
	BaoQuan      string         `json:"bao_quan"`
	DongGoi      string         `json:"dong_goi"`
	PhanLoai     sql.NullString `json:"phan_loai"`
	DangBaoChe   string         `json:"dang_bao_che"`
	TieuChuanSx  string         `json:"tieu_chuan_sx"`
	CongTySx     int32          `json:"cong_ty_sx"`
	CongTyDk     int32          `json:"cong_ty_dk"`
}

type Promotion struct {
	ID                      uuid.UUID       `json:"id"`
	Code                    string          `json:"code"`
	Type                    sql.NullString  `json:"type"`
	Title                   sql.NullString  `json:"title"`
	ConditionsText          sql.NullString  `json:"conditions_text"`
	ConditionsPointCustomer sql.NullInt32   `json:"conditions_point_customer"`
	MinValue                sql.NullFloat64 `json:"min_value"`
	IsDiscountPercent       bool            `json:"is_discount_percent"`
	ValueDiscount           float64         `json:"value_discount"`
	MaxDiscount             sql.NullFloat64 `json:"max_discount"`
	// null: vố số, int: số lần cụ thể
	TimeApply           sql.NullInt32 `json:"time_apply"`
	DateStart           sql.NullTime  `json:"date_start"`
	DateEnd             sql.NullTime  `json:"date_end"`
	ApplyMultipleTimes  bool          `json:"apply_multiple_times"`
	ApplySimultaneously bool          `json:"apply_simultaneously"`
	// true: áp dụng, false: vô hiệu
	Status      bool          `json:"status"`
	Company     sql.NullInt32 `json:"company"`
	UserCreated int32         `json:"user_created"`
	UserUpdated sql.NullInt32 `json:"user_updated"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type PromotionItem struct {
	ID                uuid.UUID     `json:"id"`
	MinBuy            sql.NullInt32 `json:"min_buy"`
	AmountGift        sql.NullInt32 `json:"amount_gift"`
	Promotions        uuid.UUID     `json:"promotions"`
	ApplicableVariant sql.NullInt32 `json:"applicable_variant"`
	ApplicableService sql.NullInt32 `json:"applicable_service"`
	Variant           sql.NullInt32 `json:"variant"`
	Service           sql.NullInt32 `json:"service"`
}

type PromotionType struct {
	Code string `json:"code"`
	// 1: khuyến mãi giảm giá, 2: khuyến mãi tặng sp
	Title sql.NullString `json:"title"`
}

type Province struct {
	Code                   string        `json:"code"`
	Name                   string        `json:"name"`
	NameEn                 string        `json:"name_en"`
	FullName               string        `json:"full_name"`
	FullNameEn             string        `json:"full_name_en"`
	CodeName               string        `json:"code_name"`
	AdministrativeUnitID   sql.NullInt32 `json:"administrative_unit_id"`
	AdministrativeRegionID sql.NullInt32 `json:"administrative_region_id"`
}

type Role struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Title       string         `json:"title"`
	Note        sql.NullString `json:"note"`
	Company     sql.NullInt32  `json:"company"`
	UserCreated int32          `json:"user_created"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RoleItem struct {
	ID    int32        `json:"id"`
	Roles int32        `json:"roles"`
	App   string       `json:"app"`
	Value sql.NullBool `json:"value"`
}

type Service struct {
	ID           int32          `json:"id"`
	Image        sql.NullInt32  `json:"image"`
	Code         string         `json:"code"`
	Title        string         `json:"title"`
	Entity       sql.NullString `json:"entity"`
	Staff        int32          `json:"staff"`
	Frequency    sql.NullString `json:"frequency"`
	ReminderTime sql.NullInt32  `json:"reminder_time"`
	Unit         string         `json:"unit"`
	Price        float64        `json:"price"`
	Description  sql.NullString `json:"description"`
	Company      int32          `json:"company"`
	UserCreated  int32          `json:"user_created"`
	UserUpdated  sql.NullInt32  `json:"user_updated"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ServiceOrderItem struct {
	ID         int32         `json:"id"`
	Order      int32         `json:"order"`
	Service    sql.NullInt32 `json:"service"`
	UnitPrice  float64       `json:"unit_price"`
	Discount   float64       `json:"discount"`
	TotalPrice float64       `json:"total_price"`
	Quantity   sql.NullInt32 `json:"quantity"`
}

type ServiceVariant struct {
	ID      int32         `json:"id"`
	Service sql.NullInt32 `json:"service"`
	Variant sql.NullInt32 `json:"variant"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Suplier struct {
	ID         int32          `json:"id"`
	Code       string         `json:"code"`
	Name       string         `json:"name"`
	DeputyName string         `json:"deputy_name"`
	Phone      string         `json:"phone"`
	Email      sql.NullString `json:"email"`
	Address    sql.NullInt32  `json:"address"`
	Company    sql.NullInt32  `json:"company"`
}

type Ticket struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Type        sql.NullInt32  `json:"type"`
	Status      sql.NullInt32  `json:"status"`
	Note        sql.NullString `json:"note"`
	Qr          sql.NullInt32  `json:"qr"`
	ExportTo    sql.NullInt32  `json:"export_to"`
	ImportFrom  sql.NullInt32  `json:"import_from"`
	TotalPrice  float64        `json:"total_price"`
	Warehouse   int32          `json:"warehouse"`
	UserCreated int32          `json:"user_created"`
	UserUpdated sql.NullInt32  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type TicketStatus struct {
	ID    int32  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type TicketType struct {
	ID    int32  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type Unit struct {
	ID          int32           `json:"id"`
	Name        string          `json:"name"`
	SellPrice   float64         `json:"sell_price"`
	ImportPrice float64         `json:"import_price"`
	Weight      sql.NullFloat64 `json:"weight"`
	WeightUnit  sql.NullString  `json:"weight_unit"`
	UserCreated int32           `json:"user_created"`
	UserUpdated sql.NullInt32   `json:"user_updated"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type UnitChange struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Value       int64         `json:"value"`
	SellPrice   float64       `json:"sell_price"`
	Unit        int32         `json:"unit"`
	UserCreated int32         `json:"user_created"`
	UserUpdated sql.NullInt32 `json:"user_updated"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	CreatedAt   time.Time     `json:"created_at"`
}

type Variant struct {
	ID               int32           `json:"id"`
	Name             string          `json:"name"`
	Code             string          `json:"code"`
	Barcode          sql.NullString  `json:"barcode"`
	DecisionNumber   sql.NullString  `json:"decision_number"`
	RegisterNumber   sql.NullString  `json:"register_number"`
	Longevity        sql.NullString  `json:"longevity"`
	Vat              sql.NullFloat64 `json:"vat"`
	Product          int32           `json:"product"`
	UserCreated      int32           `json:"user_created"`
	UserUpdated      sql.NullInt32   `json:"user_updated"`
	UpdatedAt        sql.NullTime    `json:"updated_at"`
	CreatedAt        time.Time       `json:"created_at"`
	InitialInventory int32           `json:"initial_inventory"`
	RealInventory    int32           `json:"real_inventory"`
}

type VariantMedium struct {
	ID      int32 `json:"id"`
	Variant int32 `json:"variant"`
	Media   int32 `json:"media"`
}

type Verify struct {
	ID         int32     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}

type Ward struct {
	Code                 string         `json:"code"`
	Name                 string         `json:"name"`
	NameEn               string         `json:"name_en"`
	FullName             string         `json:"full_name"`
	FullNameEn           string         `json:"full_name_en"`
	CodeName             string         `json:"code_name"`
	DistrictCode         sql.NullString `json:"district_code"`
	AdministrativeUnitID sql.NullInt32  `json:"administrative_unit_id"`
}

type Warehouse struct {
	ID        int32         `json:"id"`
	Address   sql.NullInt32 `json:"address"`
	Companies sql.NullInt32 `json:"companies"`
	Name      string        `json:"name"`
	Code      string        `json:"code"`
}
