// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	Type              int64     `json:"type"`
	IsVerify          bool      `json:"is_verify"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type AccountCompany struct {
	ID      int64 `json:"id"`
	Account int64 `json:"account"`
	Company int64 `json:"company"`
}

type AccountMedium struct {
	ID      int64 `json:"id"`
	Account int64 `json:"account"`
	Media   int64 `json:"media"`
}

type AccountType struct {
	ID    int64  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type Address struct {
	ID          int64          `json:"id"`
	Lat         float64        `json:"lat"`
	Lng         float64        `json:"lng"`
	Title       string         `json:"title"`
	UserCreated int64          `json:"user_created"`
	CreatedAt   time.Time      `json:"created_at"`
	Province    sql.NullString `json:"province"`
	District    sql.NullString `json:"district"`
	Ward        sql.NullString `json:"ward"`
}

type AdministrativeRegion struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	NameEn     string `json:"name_en"`
	CodeName   string `json:"code_name"`
	CodeNameEn string `json:"code_name_en"`
}

type AdministrativeUnit struct {
	ID          int64  `json:"id"`
	FullName    string `json:"full_name"`
	FullNameEn  string `json:"full_name_en"`
	ShortName   string `json:"short_name"`
	ShortNameEn string `json:"short_name_en"`
	CodeName    string `json:"code_name"`
	CodeNameEn  string `json:"code_name_en"`
}

type Classify struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type Company struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	TaxCode     sql.NullString `json:"tax_code"`
	Phone       sql.NullString `json:"phone"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	Owner       int64          `json:"owner"`
	Address     int64          `json:"address"`
}

type CompanyPharma struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	Code              sql.NullString `json:"code"`
	Country           sql.NullString `json:"country"`
	Address           sql.NullString `json:"address"`
	CompanyPharmaType sql.NullString `json:"company_pharma_type"`
	CreatedAt         time.Time      `json:"created_at"`
}

type CompanyPharmaType struct {
	ID    int64  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type Customer struct {
	ID          int64          `json:"id"`
	FullName    string         `json:"full_name"`
	Code        string         `json:"code"`
	Company     sql.NullInt64  `json:"company"`
	Address     sql.NullInt64  `json:"address"`
	Email       sql.NullString `json:"email"`
	Birthday    sql.NullTime   `json:"birthday"`
	UserCreated int64          `json:"user_created"`
	UserUpdated sql.NullInt64  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type District struct {
	Code                 string         `json:"code"`
	Name                 string         `json:"name"`
	NameEn               string         `json:"name_en"`
	FullName             string         `json:"full_name"`
	FullNameEn           string         `json:"full_name_en"`
	CodeName             string         `json:"code_name"`
	ProvinceCode         sql.NullString `json:"province_code"`
	AdministrativeUnitID sql.NullInt64  `json:"administrative_unit_id"`
}

type Ingredient struct {
	ID     int32   `json:"id"`
	Name   string  `json:"name"`
	Weight float64 `json:"weight"`
	Unit   string  `json:"unit"`
}

type Media struct {
	ID       int64  `json:"id"`
	MediaUrl string `json:"media_url"`
}

type Order struct {
	ID          int64          `json:"id"`
	Vat         string         `json:"vat"`
	TotalPrice  string         `json:"total_price"`
	Description sql.NullString `json:"description"`
	Customer    sql.NullInt64  `json:"customer"`
	Status      int64          `json:"status"`
	Type        sql.NullInt64  `json:"type"`
	Ticket      sql.NullInt64  `json:"ticket"`
	Qr          sql.NullInt64  `json:"qr"`
}

type OrderItem struct {
	ID      int64         `json:"id"`
	Order   sql.NullInt64 `json:"order"`
	Variant sql.NullInt64 `json:"variant"`
	Value   int32         `json:"value"`
}

type OrderStatus struct {
	ID    int64  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type OrderType struct {
	ID    int64  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type PreparationType struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type PriceList struct {
	ID          int64         `json:"id"`
	VariantCode string        `json:"variant_code"`
	VariantName string        `json:"variant_name"`
	PriceImport float64       `json:"price_import"`
	PriceSell   float64       `json:"price_sell"`
	Unit        int64         `json:"unit"`
	UserCreated int64         `json:"user_created"`
	UserUpdated sql.NullInt64 `json:"user_updated"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	CreatedAt   time.Time     `json:"created_at"`
}

type PriceListLog struct {
	ID             int64     `json:"id"`
	OldPriceImport float64   `json:"old_price_import"`
	NewPriceImport float64   `json:"new_price_import"`
	OldPriceSell   float64   `json:"old_price_sell"`
	NewPriceSell   float64   `json:"new_price_sell"`
	PriceList      int64     `json:"price_list"`
	UserUpdated    int64     `json:"user_updated"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Product struct {
	ID              int64          `json:"id"`
	Name            string         `json:"name"`
	Code            string         `json:"code"`
	ProductCategory sql.NullInt64  `json:"product_category"`
	Type            sql.NullInt64  `json:"type"`
	Unit            int64          `json:"unit"`
	Company         sql.NullInt64  `json:"company"`
	UserCreated     int64          `json:"user_created"`
	UserUpdated     sql.NullInt64  `json:"user_updated"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	CreatedAt       time.Time      `json:"created_at"`
	Taduoc          sql.NullString `json:"taduoc"`
	Nongdo          sql.NullString `json:"nongdo"`
	Lieudung        string         `json:"lieudung"`
	Chidinh         string         `json:"chidinh"`
	Chongchidinh    sql.NullString `json:"chongchidinh"`
	Congdung        string         `json:"congdung"`
	Tacdungphu      string         `json:"tacdungphu"`
	Thantrong       string         `json:"thantrong"`
	Tuongtac        sql.NullString `json:"tuongtac"`
	Baoquan         string         `json:"baoquan"`
	Donggoi         string         `json:"donggoi"`
	Noisx           string         `json:"noisx"`
	Congtysx        string         `json:"congtysx"`
	Congtydk        string         `json:"congtydk"`
	Active          bool           `json:"active"`
	CongTySx        sql.NullInt64  `json:"congTySx"`
	CongTyDk        sql.NullInt64  `json:"congTyDk"`
	Brand           int32          `json:"brand"`
}

type ProductBrand struct {
	ID          int32     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	UserCreated int64     `json:"user_created"`
	CreatedAt   time.Time `json:"created_at"`
}

type ProductCategory struct {
	ID          int32     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	UserCreated int64     `json:"user_created"`
	CreatedAt   time.Time `json:"created_at"`
}

type ProductIngredient struct {
	ID         int64 `json:"id"`
	Product    int64 `json:"product"`
	Ingredient int32 `json:"ingredient"`
}

type ProductMedium struct {
	ID      int64         `json:"id"`
	Product sql.NullInt64 `json:"product"`
	Media   sql.NullInt64 `json:"media"`
}

type ProductType struct {
	ID          int32     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	UserCreated int64     `json:"user_created"`
	CreatedAt   time.Time `json:"created_at"`
}

type ProductionStandard struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type ProductsBank struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Code         string         `json:"code"`
	TaDuoc       sql.NullString `json:"taDuoc"`
	NongDo       sql.NullString `json:"nongDo"`
	LieuDung     string         `json:"lieuDung"`
	ChiDinh      string         `json:"chiDinh"`
	ChongChiDinh sql.NullString `json:"chongChiDinh"`
	CongDung     string         `json:"congDung"`
	TacDungPhu   string         `json:"tacDungPhu"`
	ThanTrong    string         `json:"thanTrong"`
	TuongTac     sql.NullString `json:"tuongTac"`
	BaoQuan      string         `json:"baoQuan"`
	DongGoi      string         `json:"dongGoi"`
	PhanLoai     sql.NullString `json:"phanLoai"`
	DangBaoche   string         `json:"dangBaoche"`
	TieuChuanSx  string         `json:"tieuChuanSx"`
	CongTySx     int64          `json:"congTySx"`
	CongTyDk     int64          `json:"congTyDk"`
}

type Province struct {
	Code                   string        `json:"code"`
	Name                   string        `json:"name"`
	NameEn                 string        `json:"name_en"`
	FullName               string        `json:"full_name"`
	FullNameEn             string        `json:"full_name_en"`
	CodeName               string        `json:"code_name"`
	AdministrativeUnitID   sql.NullInt64 `json:"administrative_unit_id"`
	AdministrativeRegionID sql.NullInt64 `json:"administrative_region_id"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Ticket struct {
	ID          int64          `json:"id"`
	Code        string         `json:"code"`
	Type        int64          `json:"type"`
	Status      int64          `json:"status"`
	Note        sql.NullString `json:"note"`
	Qr          sql.NullInt64  `json:"qr"`
	ExportFrom  int64          `json:"export_from"`
	ImportTo    int64          `json:"import_to"`
	UserCreated int64          `json:"user_created"`
	UserUpdated sql.NullInt64  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type TicketStatus struct {
	ID    int64  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type TicketType struct {
	ID    int64  `json:"id"`
	Code  string `json:"code"`
	Title string `json:"title"`
}

type Unit struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	SellPrice   string         `json:"sell_price"`
	ImportPrice string         `json:"import_price"`
	Weight      sql.NullString `json:"weight"`
	WeightUnit  sql.NullString `json:"weight_unit"`
	UserCreated int64          `json:"user_created"`
	UserUpdated sql.NullInt64  `json:"user_updated"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type UnitChange struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	Value       int64         `json:"value"`
	SellPrice   string        `json:"sell_price"`
	Unit        sql.NullInt64 `json:"unit"`
	UserCreated int64         `json:"user_created"`
	UserUpdated sql.NullInt64 `json:"user_updated"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	CreatedAt   time.Time     `json:"created_at"`
}

type Variant struct {
	ID             int64         `json:"id"`
	Name           string        `json:"name"`
	Code           string        `json:"code"`
	Barcode        string        `json:"barcode"`
	DecisionNumber string        `json:"decision_number"`
	RegisterNumber string        `json:"register_number"`
	Vat            string        `json:"vat"`
	Product        sql.NullInt64 `json:"product"`
	UserCreated    int64         `json:"user_created"`
	UserUpdated    sql.NullInt64 `json:"user_updated"`
	UpdatedAt      sql.NullTime  `json:"updated_at"`
	CreatedAt      time.Time     `json:"created_at"`
	Longevity      string        `json:"longevity"`
}

type VariantMedium struct {
	ID      int64 `json:"id"`
	Variant int64 `json:"variant"`
	Media   int64 `json:"media"`
}

type Verify struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}

type Ward struct {
	Code                 string         `json:"code"`
	Name                 string         `json:"name"`
	NameEn               string         `json:"name_en"`
	FullName             string         `json:"full_name"`
	FullNameEn           string         `json:"full_name_en"`
	CodeName             string         `json:"code_name"`
	DistrictCode         sql.NullString `json:"district_code"`
	AdministrativeUnitID sql.NullInt64  `json:"administrative_unit_id"`
}

type Warehouse struct {
	ID        int64 `json:"id"`
	Address   int64 `json:"address"`
	Companies int64 `json:"companies"`
}
