// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: payloads/address_payload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat      float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng      float32 `protobuf:"fixed32,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Province string  `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	District string  `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"`
	Ward     *string `protobuf:"bytes,5,opt,name=ward,proto3,oneof" json:"ward,omitempty"`
	Title    string  `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *AddressCreate) Reset() {
	*x = AddressCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_address_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressCreate) ProtoMessage() {}

func (x *AddressCreate) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_address_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressCreate.ProtoReflect.Descriptor instead.
func (*AddressCreate) Descriptor() ([]byte, []int) {
	return file_payloads_address_payload_proto_rawDescGZIP(), []int{0}
}

func (x *AddressCreate) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *AddressCreate) GetLng() float32 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *AddressCreate) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressCreate) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressCreate) GetWard() string {
	if x != nil && x.Ward != nil {
		return *x.Ward
	}
	return ""
}

func (x *AddressCreate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_payloads_address_payload_proto protoreflect.FileDescriptor

var file_payloads_address_payload_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0xa3, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x77, 0x61, 0x72, 0x64, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x77, 0x61, 0x72, 0x64, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x61, 0x6e, 0x67, 0x4c, 0x6f,
	0x6e, 0x67, 0x32, 0x35, 0x30, 0x32, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x67, 0x6f, 0x5f,
	0x62, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_payloads_address_payload_proto_rawDescOnce sync.Once
	file_payloads_address_payload_proto_rawDescData = file_payloads_address_payload_proto_rawDesc
)

func file_payloads_address_payload_proto_rawDescGZIP() []byte {
	file_payloads_address_payload_proto_rawDescOnce.Do(func() {
		file_payloads_address_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_payloads_address_payload_proto_rawDescData)
	})
	return file_payloads_address_payload_proto_rawDescData
}

var file_payloads_address_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_payloads_address_payload_proto_goTypes = []interface{}{
	(*AddressCreate)(nil), // 0: pb.AddressCreate
}
var file_payloads_address_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payloads_address_payload_proto_init() }
func file_payloads_address_payload_proto_init() {
	if File_payloads_address_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_payloads_address_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_payloads_address_payload_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payloads_address_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payloads_address_payload_proto_goTypes,
		DependencyIndexes: file_payloads_address_payload_proto_depIdxs,
		MessageInfos:      file_payloads_address_payload_proto_msgTypes,
	}.Build()
	File_payloads_address_payload_proto = out.File
	file_payloads_address_payload_proto_rawDesc = nil
	file_payloads_address_payload_proto_goTypes = nil
	file_payloads_address_payload_proto_depIdxs = nil
}
