// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: rpc/order/rpc_create_payment_item_order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentItemType int32

const (
	PaymentItemType_CASH    PaymentItemType = 0
	PaymentItemType_BANKING PaymentItemType = 1
	PaymentItemType_DEBIT   PaymentItemType = 2
)

// Enum value maps for PaymentItemType.
var (
	PaymentItemType_name = map[int32]string{
		0: "CASH",
		1: "BANKING",
		2: "DEBIT",
	}
	PaymentItemType_value = map[string]int32{
		"CASH":    0,
		"BANKING": 1,
		"DEBIT":   2,
	}
)

func (x PaymentItemType) Enum() *PaymentItemType {
	p := new(PaymentItemType)
	*p = x
	return p
}

func (x PaymentItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_order_rpc_create_payment_item_order_proto_enumTypes[0].Descriptor()
}

func (PaymentItemType) Type() protoreflect.EnumType {
	return &file_rpc_order_rpc_create_payment_item_order_proto_enumTypes[0]
}

func (x PaymentItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentItemType.Descriptor instead.
func (PaymentItemType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_order_rpc_create_payment_item_order_proto_rawDescGZIP(), []int{0}
}

type PaymentItemOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    PaymentItemType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PaymentItemType" json:"type,omitempty"`
	Value   float32         `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	OrderId int32           `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *PaymentItemOrderRequest) Reset() {
	*x = PaymentItemOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_order_rpc_create_payment_item_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentItemOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentItemOrderRequest) ProtoMessage() {}

func (x *PaymentItemOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_order_rpc_create_payment_item_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentItemOrderRequest.ProtoReflect.Descriptor instead.
func (*PaymentItemOrderRequest) Descriptor() ([]byte, []int) {
	return file_rpc_order_rpc_create_payment_item_order_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentItemOrderRequest) GetType() PaymentItemType {
	if x != nil {
		return x.Type
	}
	return PaymentItemType_CASH
}

func (x *PaymentItemOrderRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PaymentItemOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type PaymentItemOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message      string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageTrans string `protobuf:"bytes,3,opt,name=message_trans,json=messageTrans,proto3" json:"message_trans,omitempty"`
	Log          string `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *PaymentItemOrderResponse) Reset() {
	*x = PaymentItemOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_order_rpc_create_payment_item_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentItemOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentItemOrderResponse) ProtoMessage() {}

func (x *PaymentItemOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_order_rpc_create_payment_item_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentItemOrderResponse.ProtoReflect.Descriptor instead.
func (*PaymentItemOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_order_rpc_create_payment_item_order_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentItemOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentItemOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaymentItemOrderResponse) GetMessageTrans() string {
	if x != nil {
		return x.MessageTrans
	}
	return ""
}

func (x *PaymentItemOrderResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_rpc_order_rpc_create_payment_item_order_proto protoreflect.FileDescriptor

var file_rpc_order_rpc_create_payment_item_order_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x5f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x14, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x17, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7f,
	0x0a, 0x18, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x6f, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x2a,
	0x33, 0x0a, 0x0f, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x53, 0x48, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x42, 0x41, 0x4e, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42,
	0x49, 0x54, 0x10, 0x02, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x61, 0x6e, 0x67, 0x4c, 0x6f, 0x6e, 0x67, 0x32, 0x35, 0x30, 0x32,
	0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x67, 0x6f, 0x5f, 0x62, 0x65, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_order_rpc_create_payment_item_order_proto_rawDescOnce sync.Once
	file_rpc_order_rpc_create_payment_item_order_proto_rawDescData = file_rpc_order_rpc_create_payment_item_order_proto_rawDesc
)

func file_rpc_order_rpc_create_payment_item_order_proto_rawDescGZIP() []byte {
	file_rpc_order_rpc_create_payment_item_order_proto_rawDescOnce.Do(func() {
		file_rpc_order_rpc_create_payment_item_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_order_rpc_create_payment_item_order_proto_rawDescData)
	})
	return file_rpc_order_rpc_create_payment_item_order_proto_rawDescData
}

var file_rpc_order_rpc_create_payment_item_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_order_rpc_create_payment_item_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_order_rpc_create_payment_item_order_proto_goTypes = []interface{}{
	(PaymentItemType)(0),             // 0: pb.PaymentItemType
	(*PaymentItemOrderRequest)(nil),  // 1: pb.PaymentItemOrderRequest
	(*PaymentItemOrderResponse)(nil), // 2: pb.PaymentItemOrderResponse
}
var file_rpc_order_rpc_create_payment_item_order_proto_depIdxs = []int32{
	0, // 0: pb.PaymentItemOrderRequest.type:type_name -> pb.PaymentItemType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_order_rpc_create_payment_item_order_proto_init() }
func file_rpc_order_rpc_create_payment_item_order_proto_init() {
	if File_rpc_order_rpc_create_payment_item_order_proto != nil {
		return
	}
	file_entities_order_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_order_rpc_create_payment_item_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentItemOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_order_rpc_create_payment_item_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentItemOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_order_rpc_create_payment_item_order_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_order_rpc_create_payment_item_order_proto_goTypes,
		DependencyIndexes: file_rpc_order_rpc_create_payment_item_order_proto_depIdxs,
		EnumInfos:         file_rpc_order_rpc_create_payment_item_order_proto_enumTypes,
		MessageInfos:      file_rpc_order_rpc_create_payment_item_order_proto_msgTypes,
	}.Build()
	File_rpc_order_rpc_create_payment_item_order_proto = out.File
	file_rpc_order_rpc_create_payment_item_order_proto_rawDesc = nil
	file_rpc_order_rpc_create_payment_item_order_proto_goTypes = nil
	file_rpc_order_rpc_create_payment_item_order_proto_depIdxs = nil
}
