// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: rpc/supplier/rpc_supplier_create.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupplierCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    *string         `protobuf:"bytes,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Name    string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Deputy  string          `protobuf:"bytes,3,opt,name=deputy,proto3" json:"deputy,omitempty"`
	Phone   string          `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Address *AddressPayload `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Email   *string         `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Company int32           `protobuf:"varint,7,opt,name=company,proto3" json:"company,omitempty"`
}

func (x *SupplierCreateRequest) Reset() {
	*x = SupplierCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_supplier_rpc_supplier_create_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplierCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierCreateRequest) ProtoMessage() {}

func (x *SupplierCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_supplier_rpc_supplier_create_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierCreateRequest.ProtoReflect.Descriptor instead.
func (*SupplierCreateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_supplier_rpc_supplier_create_proto_rawDescGZIP(), []int{0}
}

func (x *SupplierCreateRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *SupplierCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SupplierCreateRequest) GetDeputy() string {
	if x != nil {
		return x.Deputy
	}
	return ""
}

func (x *SupplierCreateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SupplierCreateRequest) GetAddress() *AddressPayload {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SupplierCreateRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *SupplierCreateRequest) GetCompany() int32 {
	if x != nil {
		return x.Company
	}
	return 0
}

type SupplierCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details int32  `protobuf:"varint,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *SupplierCreateResponse) Reset() {
	*x = SupplierCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_supplier_rpc_supplier_create_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplierCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierCreateResponse) ProtoMessage() {}

func (x *SupplierCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_supplier_rpc_supplier_create_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierCreateResponse.ProtoReflect.Descriptor instead.
func (*SupplierCreateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_supplier_rpc_supplier_create_proto_rawDescGZIP(), []int{1}
}

func (x *SupplierCreateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SupplierCreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SupplierCreateResponse) GetDetails() int32 {
	if x != nil {
		return x.Details
	}
	return 0
}

var File_rpc_supplier_rpc_supplier_create_proto protoreflect.FileDescriptor

var file_rpc_supplier_rpc_supplier_create_proto_rawDesc = []byte{
	0x0a, 0x26, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x2f, 0x72,
	0x70, 0x63, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x16, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x15, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x70, 0x75, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x70,
	0x75, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x60, 0x0a, 0x16, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x48, 0x6f, 0x61, 0x6e, 0x67, 0x4c, 0x6f, 0x6e, 0x67, 0x32, 0x35, 0x30, 0x32, 0x2f, 0x70, 0x68,
	0x61, 0x72, 0x6d, 0x61, 0x67, 0x6f, 0x5f, 0x62, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_supplier_rpc_supplier_create_proto_rawDescOnce sync.Once
	file_rpc_supplier_rpc_supplier_create_proto_rawDescData = file_rpc_supplier_rpc_supplier_create_proto_rawDesc
)

func file_rpc_supplier_rpc_supplier_create_proto_rawDescGZIP() []byte {
	file_rpc_supplier_rpc_supplier_create_proto_rawDescOnce.Do(func() {
		file_rpc_supplier_rpc_supplier_create_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_supplier_rpc_supplier_create_proto_rawDescData)
	})
	return file_rpc_supplier_rpc_supplier_create_proto_rawDescData
}

var file_rpc_supplier_rpc_supplier_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_supplier_rpc_supplier_create_proto_goTypes = []interface{}{
	(*SupplierCreateRequest)(nil),  // 0: pb.SupplierCreateRequest
	(*SupplierCreateResponse)(nil), // 1: pb.SupplierCreateResponse
	(*AddressPayload)(nil),         // 2: pb.AddressPayload
}
var file_rpc_supplier_rpc_supplier_create_proto_depIdxs = []int32{
	2, // 0: pb.SupplierCreateRequest.address:type_name -> pb.AddressPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_supplier_rpc_supplier_create_proto_init() }
func file_rpc_supplier_rpc_supplier_create_proto_init() {
	if File_rpc_supplier_rpc_supplier_create_proto != nil {
		return
	}
	file_entities_address_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_supplier_rpc_supplier_create_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplierCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_supplier_rpc_supplier_create_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplierCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_supplier_rpc_supplier_create_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_supplier_rpc_supplier_create_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_supplier_rpc_supplier_create_proto_goTypes,
		DependencyIndexes: file_rpc_supplier_rpc_supplier_create_proto_depIdxs,
		MessageInfos:      file_rpc_supplier_rpc_supplier_create_proto_msgTypes,
	}.Build()
	File_rpc_supplier_rpc_supplier_create_proto = out.File
	file_rpc_supplier_rpc_supplier_create_proto_rawDesc = nil
	file_rpc_supplier_rpc_supplier_create_proto_goTypes = nil
	file_rpc_supplier_rpc_supplier_create_proto_depIdxs = nil
}
