// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: rpc/warehouse/rpc_ticket_update_status.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketUpdateStatusRequest_STATUS int32

const (
	TicketUpdateStatusRequest_NEW        TicketUpdateStatusRequest_STATUS = 0
	TicketUpdateStatusRequest_IN_PROCESS TicketUpdateStatusRequest_STATUS = 1
	TicketUpdateStatusRequest_COMPLETE   TicketUpdateStatusRequest_STATUS = 2
	TicketUpdateStatusRequest_CANCEL     TicketUpdateStatusRequest_STATUS = 3
)

// Enum value maps for TicketUpdateStatusRequest_STATUS.
var (
	TicketUpdateStatusRequest_STATUS_name = map[int32]string{
		0: "NEW",
		1: "IN_PROCESS",
		2: "COMPLETE",
		3: "CANCEL",
	}
	TicketUpdateStatusRequest_STATUS_value = map[string]int32{
		"NEW":        0,
		"IN_PROCESS": 1,
		"COMPLETE":   2,
		"CANCEL":     3,
	}
)

func (x TicketUpdateStatusRequest_STATUS) Enum() *TicketUpdateStatusRequest_STATUS {
	p := new(TicketUpdateStatusRequest_STATUS)
	*p = x
	return p
}

func (x TicketUpdateStatusRequest_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketUpdateStatusRequest_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_warehouse_rpc_ticket_update_status_proto_enumTypes[0].Descriptor()
}

func (TicketUpdateStatusRequest_STATUS) Type() protoreflect.EnumType {
	return &file_rpc_warehouse_rpc_ticket_update_status_proto_enumTypes[0]
}

func (x TicketUpdateStatusRequest_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketUpdateStatusRequest_STATUS.Descriptor instead.
func (TicketUpdateStatusRequest_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescGZIP(), []int{0, 0}
}

type TicketUpdateStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32                            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status TicketUpdateStatusRequest_STATUS `protobuf:"varint,2,opt,name=status,proto3,enum=pb.TicketUpdateStatusRequest_STATUS" json:"status,omitempty"`
	Note   string                           `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *TicketUpdateStatusRequest) Reset() {
	*x = TicketUpdateStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketUpdateStatusRequest) ProtoMessage() {}

func (x *TicketUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*TicketUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescGZIP(), []int{0}
}

func (x *TicketUpdateStatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketUpdateStatusRequest) GetStatus() TicketUpdateStatusRequest_STATUS {
	if x != nil {
		return x.Status
	}
	return TicketUpdateStatusRequest_NEW
}

func (x *TicketUpdateStatusRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type TicketUpdateStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TicketUpdateStatusResponse) Reset() {
	*x = TicketUpdateStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketUpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketUpdateStatusResponse) ProtoMessage() {}

func (x *TicketUpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketUpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*TicketUpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescGZIP(), []int{1}
}

func (x *TicketUpdateStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TicketUpdateStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_warehouse_rpc_ticket_update_status_proto protoreflect.FileDescriptor

var file_rpc_warehouse_rpc_ticket_update_status_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f,
	0x72, 0x70, 0x63, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x18, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x77, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69,
	0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x01, 0x0a,
	0x19, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x5e, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x42, 0x20, 0x92, 0x41, 0x1d, 0x32, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x3b,
	0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x03, 0x22, 0x4a, 0x0a, 0x1a, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x61, 0x6e, 0x67, 0x4c, 0x6f, 0x6e, 0x67, 0x32,
	0x35, 0x30, 0x32, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x67, 0x6f, 0x5f, 0x62, 0x65, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescOnce sync.Once
	file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescData = file_rpc_warehouse_rpc_ticket_update_status_proto_rawDesc
)

func file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescGZIP() []byte {
	file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescOnce.Do(func() {
		file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescData)
	})
	return file_rpc_warehouse_rpc_ticket_update_status_proto_rawDescData
}

var file_rpc_warehouse_rpc_ticket_update_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_warehouse_rpc_ticket_update_status_proto_goTypes = []interface{}{
	(TicketUpdateStatusRequest_STATUS)(0), // 0: pb.TicketUpdateStatusRequest.STATUS
	(*TicketUpdateStatusRequest)(nil),     // 1: pb.TicketUpdateStatusRequest
	(*TicketUpdateStatusResponse)(nil),    // 2: pb.TicketUpdateStatusResponse
}
var file_rpc_warehouse_rpc_ticket_update_status_proto_depIdxs = []int32{
	0, // 0: pb.TicketUpdateStatusRequest.status:type_name -> pb.TicketUpdateStatusRequest.STATUS
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_warehouse_rpc_ticket_update_status_proto_init() }
func file_rpc_warehouse_rpc_ticket_update_status_proto_init() {
	if File_rpc_warehouse_rpc_ticket_update_status_proto != nil {
		return
	}
	file_entities_warehouse_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketUpdateStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketUpdateStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_warehouse_rpc_ticket_update_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_warehouse_rpc_ticket_update_status_proto_goTypes,
		DependencyIndexes: file_rpc_warehouse_rpc_ticket_update_status_proto_depIdxs,
		EnumInfos:         file_rpc_warehouse_rpc_ticket_update_status_proto_enumTypes,
		MessageInfos:      file_rpc_warehouse_rpc_ticket_update_status_proto_msgTypes,
	}.Build()
	File_rpc_warehouse_rpc_ticket_update_status_proto = out.File
	file_rpc_warehouse_rpc_ticket_update_status_proto_rawDesc = nil
	file_rpc_warehouse_rpc_ticket_update_status_proto_goTypes = nil
	file_rpc_warehouse_rpc_ticket_update_status_proto_depIdxs = nil
}
