// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: rpc/product/rpc_company_pharma.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyPharmaCreateRequest_TypeEnum int32

const (
	CompanyPharmaCreateRequest_PRODUCTION CompanyPharmaCreateRequest_TypeEnum = 0
	CompanyPharmaCreateRequest_REGISTERED CompanyPharmaCreateRequest_TypeEnum = 1
)

// Enum value maps for CompanyPharmaCreateRequest_TypeEnum.
var (
	CompanyPharmaCreateRequest_TypeEnum_name = map[int32]string{
		0: "PRODUCTION",
		1: "REGISTERED",
	}
	CompanyPharmaCreateRequest_TypeEnum_value = map[string]int32{
		"PRODUCTION": 0,
		"REGISTERED": 1,
	}
)

func (x CompanyPharmaCreateRequest_TypeEnum) Enum() *CompanyPharmaCreateRequest_TypeEnum {
	p := new(CompanyPharmaCreateRequest_TypeEnum)
	*p = x
	return p
}

func (x CompanyPharmaCreateRequest_TypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompanyPharmaCreateRequest_TypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_product_rpc_company_pharma_proto_enumTypes[0].Descriptor()
}

func (CompanyPharmaCreateRequest_TypeEnum) Type() protoreflect.EnumType {
	return &file_rpc_product_rpc_company_pharma_proto_enumTypes[0]
}

func (x CompanyPharmaCreateRequest_TypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompanyPharmaCreateRequest_TypeEnum.Descriptor instead.
func (CompanyPharmaCreateRequest_TypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{2, 0}
}

// TODO: List
type CompanyPharmaListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page   *int32  `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit  *int32  `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Search *string `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Type   *string `protobuf:"bytes,4,opt,name=type,proto3,oneof" json:"type,omitempty"`
}

func (x *CompanyPharmaListRequest) Reset() {
	*x = CompanyPharmaListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaListRequest) ProtoMessage() {}

func (x *CompanyPharmaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaListRequest.ProtoReflect.Descriptor instead.
func (*CompanyPharmaListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyPharmaListRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *CompanyPharmaListRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *CompanyPharmaListRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *CompanyPharmaListRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type CompanyPharmaListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details []*CompanyPharma `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *CompanyPharmaListResponse) Reset() {
	*x = CompanyPharmaListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaListResponse) ProtoMessage() {}

func (x *CompanyPharmaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaListResponse.ProtoReflect.Descriptor instead.
func (*CompanyPharmaListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyPharmaListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CompanyPharmaListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompanyPharmaListResponse) GetDetails() []*CompanyPharma {
	if x != nil {
		return x.Details
	}
	return nil
}

// TODO: Create
type CompanyPharmaCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company     int32                               `protobuf:"varint,1,opt,name=company,proto3" json:"company,omitempty"`
	Code        string                              `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name        string                              `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Country     string                              `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Address     string                              `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Description string                              `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Type        CompanyPharmaCreateRequest_TypeEnum `protobuf:"varint,7,opt,name=type,proto3,enum=pb.CompanyPharmaCreateRequest_TypeEnum" json:"type,omitempty"`
}

func (x *CompanyPharmaCreateRequest) Reset() {
	*x = CompanyPharmaCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaCreateRequest) ProtoMessage() {}

func (x *CompanyPharmaCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaCreateRequest.ProtoReflect.Descriptor instead.
func (*CompanyPharmaCreateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{2}
}

func (x *CompanyPharmaCreateRequest) GetCompany() int32 {
	if x != nil {
		return x.Company
	}
	return 0
}

func (x *CompanyPharmaCreateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompanyPharmaCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyPharmaCreateRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CompanyPharmaCreateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CompanyPharmaCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompanyPharmaCreateRequest) GetType() CompanyPharmaCreateRequest_TypeEnum {
	if x != nil {
		return x.Type
	}
	return CompanyPharmaCreateRequest_PRODUCTION
}

type CompanyPharmaCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details int32  `protobuf:"varint,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *CompanyPharmaCreateResponse) Reset() {
	*x = CompanyPharmaCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaCreateResponse) ProtoMessage() {}

func (x *CompanyPharmaCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaCreateResponse.ProtoReflect.Descriptor instead.
func (*CompanyPharmaCreateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{3}
}

func (x *CompanyPharmaCreateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CompanyPharmaCreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompanyPharmaCreateResponse) GetDetails() int32 {
	if x != nil {
		return x.Details
	}
	return 0
}

// TODO: Detail
type CompanyPharmaDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CompanyPharmaDetailRequest) Reset() {
	*x = CompanyPharmaDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaDetailRequest) ProtoMessage() {}

func (x *CompanyPharmaDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaDetailRequest.ProtoReflect.Descriptor instead.
func (*CompanyPharmaDetailRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{4}
}

func (x *CompanyPharmaDetailRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CompanyPharmaDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details *CompanyPharma `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *CompanyPharmaDetailResponse) Reset() {
	*x = CompanyPharmaDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaDetailResponse) ProtoMessage() {}

func (x *CompanyPharmaDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaDetailResponse.ProtoReflect.Descriptor instead.
func (*CompanyPharmaDetailResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{5}
}

func (x *CompanyPharmaDetailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CompanyPharmaDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompanyPharmaDetailResponse) GetDetails() *CompanyPharma {
	if x != nil {
		return x.Details
	}
	return nil
}

// TODO: Update
type CompanyPharmaUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Country     string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Address     string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CompanyPharmaUpdateRequest) Reset() {
	*x = CompanyPharmaUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaUpdateRequest) ProtoMessage() {}

func (x *CompanyPharmaUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaUpdateRequest.ProtoReflect.Descriptor instead.
func (*CompanyPharmaUpdateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{6}
}

func (x *CompanyPharmaUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompanyPharmaUpdateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompanyPharmaUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyPharmaUpdateRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CompanyPharmaUpdateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CompanyPharmaUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CompanyPharmaUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details int32  `protobuf:"varint,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *CompanyPharmaUpdateResponse) Reset() {
	*x = CompanyPharmaUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaUpdateResponse) ProtoMessage() {}

func (x *CompanyPharmaUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaUpdateResponse.ProtoReflect.Descriptor instead.
func (*CompanyPharmaUpdateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{7}
}

func (x *CompanyPharmaUpdateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CompanyPharmaUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompanyPharmaUpdateResponse) GetDetails() int32 {
	if x != nil {
		return x.Details
	}
	return 0
}

// TODO: Delete
type CompanyPharmaDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CompanyPharmaDeleteRequest) Reset() {
	*x = CompanyPharmaDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaDeleteRequest) ProtoMessage() {}

func (x *CompanyPharmaDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaDeleteRequest.ProtoReflect.Descriptor instead.
func (*CompanyPharmaDeleteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{8}
}

func (x *CompanyPharmaDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CompanyPharmaDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CompanyPharmaDeleteResponse) Reset() {
	*x = CompanyPharmaDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyPharmaDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyPharmaDeleteResponse) ProtoMessage() {}

func (x *CompanyPharmaDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_rpc_company_pharma_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyPharmaDeleteResponse.ProtoReflect.Descriptor instead.
func (*CompanyPharmaDeleteResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_rpc_company_pharma_proto_rawDescGZIP(), []int{9}
}

func (x *CompanyPharmaDeleteResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CompanyPharmaDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_product_rpc_company_pharma_proto protoreflect.FileDescriptor

var file_rpc_product_rpc_company_pharma_proto_rawDesc = []byte{
	0x0a, 0x24, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x72, 0x70,
	0x63, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x70, 0x68,
	0x61, 0x72, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x18, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x76, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x22, 0xc5, 0x03, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72,
	0x6d, 0x61, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3a, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x20, 0x92, 0x41, 0x1d, 0x32, 0x11, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x20, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x32, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1e, 0x92, 0x41, 0x1b, 0x32, 0x12,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0xd2, 0x01, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x32, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1e, 0x92,
	0x41, 0x1b, 0x32, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x21, 0x92, 0x41, 0x1e, 0x32, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x3b, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x21, 0x92, 0x41, 0x1e, 0x32, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2a, 0x0a, 0x08,
	0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x44,
	0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x47, 0x49,
	0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x22, 0x65, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22,
	0x49, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x1b, 0x92, 0x41, 0x18, 0x32, 0x11,
	0x69, 0x6e, 0x74, 0x33, 0x32, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0xd2, 0x01, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x78, 0x0a, 0x1b, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x52, 0x07, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x22, 0xce, 0x02, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42,
	0x1c, 0x92, 0x41, 0x19, 0x32, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x02, 0x69, 0x64, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x32, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x1e, 0x92, 0x41, 0x1b, 0x32, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x1e, 0x92, 0x41, 0x1b, 0x32, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x21, 0x92, 0x41, 0x1e, 0x32,
	0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0xd2, 0x01, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x21, 0x92, 0x41, 0x1e, 0x32, 0x12, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0xd2, 0x01, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x65, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x49, 0x0a, 0x1a,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x1b, 0x92, 0x41, 0x18, 0x32, 0x11, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x20, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x20, 0x66, 0x69, 0x65, 0x6c, 0x64, 0xd2, 0x01,
	0x02, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x61, 0x6e, 0x67, 0x4c, 0x6f, 0x6e, 0x67, 0x32, 0x35, 0x30, 0x32,
	0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x67, 0x6f, 0x5f, 0x62, 0x65, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_product_rpc_company_pharma_proto_rawDescOnce sync.Once
	file_rpc_product_rpc_company_pharma_proto_rawDescData = file_rpc_product_rpc_company_pharma_proto_rawDesc
)

func file_rpc_product_rpc_company_pharma_proto_rawDescGZIP() []byte {
	file_rpc_product_rpc_company_pharma_proto_rawDescOnce.Do(func() {
		file_rpc_product_rpc_company_pharma_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_product_rpc_company_pharma_proto_rawDescData)
	})
	return file_rpc_product_rpc_company_pharma_proto_rawDescData
}

var file_rpc_product_rpc_company_pharma_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_product_rpc_company_pharma_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_product_rpc_company_pharma_proto_goTypes = []interface{}{
	(CompanyPharmaCreateRequest_TypeEnum)(0), // 0: pb.CompanyPharmaCreateRequest.TypeEnum
	(*CompanyPharmaListRequest)(nil),         // 1: pb.CompanyPharmaListRequest
	(*CompanyPharmaListResponse)(nil),        // 2: pb.CompanyPharmaListResponse
	(*CompanyPharmaCreateRequest)(nil),       // 3: pb.CompanyPharmaCreateRequest
	(*CompanyPharmaCreateResponse)(nil),      // 4: pb.CompanyPharmaCreateResponse
	(*CompanyPharmaDetailRequest)(nil),       // 5: pb.CompanyPharmaDetailRequest
	(*CompanyPharmaDetailResponse)(nil),      // 6: pb.CompanyPharmaDetailResponse
	(*CompanyPharmaUpdateRequest)(nil),       // 7: pb.CompanyPharmaUpdateRequest
	(*CompanyPharmaUpdateResponse)(nil),      // 8: pb.CompanyPharmaUpdateResponse
	(*CompanyPharmaDeleteRequest)(nil),       // 9: pb.CompanyPharmaDeleteRequest
	(*CompanyPharmaDeleteResponse)(nil),      // 10: pb.CompanyPharmaDeleteResponse
	(*CompanyPharma)(nil),                    // 11: pb.CompanyPharma
}
var file_rpc_product_rpc_company_pharma_proto_depIdxs = []int32{
	11, // 0: pb.CompanyPharmaListResponse.details:type_name -> pb.CompanyPharma
	0,  // 1: pb.CompanyPharmaCreateRequest.type:type_name -> pb.CompanyPharmaCreateRequest.TypeEnum
	11, // 2: pb.CompanyPharmaDetailResponse.details:type_name -> pb.CompanyPharma
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_product_rpc_company_pharma_proto_init() }
func file_rpc_product_rpc_company_pharma_proto_init() {
	if File_rpc_product_rpc_company_pharma_proto != nil {
		return
	}
	file_entities_company_pharma_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_product_rpc_company_pharma_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_product_rpc_company_pharma_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyPharmaDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_product_rpc_company_pharma_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_product_rpc_company_pharma_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_product_rpc_company_pharma_proto_goTypes,
		DependencyIndexes: file_rpc_product_rpc_company_pharma_proto_depIdxs,
		EnumInfos:         file_rpc_product_rpc_company_pharma_proto_enumTypes,
		MessageInfos:      file_rpc_product_rpc_company_pharma_proto_msgTypes,
	}.Build()
	File_rpc_product_rpc_company_pharma_proto = out.File
	file_rpc_product_rpc_company_pharma_proto_rawDesc = nil
	file_rpc_product_rpc_company_pharma_proto_goTypes = nil
	file_rpc_product_rpc_company_pharma_proto_depIdxs = nil
}
