// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: rpc/order/rpc_order_update_status.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderUpdateStatusRequest_StatusEnum int32

const (
	OrderUpdateStatusRequest_DRAFT      OrderUpdateStatusRequest_StatusEnum = 0
	OrderUpdateStatusRequest_IN_PROCESS OrderUpdateStatusRequest_StatusEnum = 1
	OrderUpdateStatusRequest_COMPLETE   OrderUpdateStatusRequest_StatusEnum = 2
	OrderUpdateStatusRequest_CANCEL     OrderUpdateStatusRequest_StatusEnum = 3
)

// Enum value maps for OrderUpdateStatusRequest_StatusEnum.
var (
	OrderUpdateStatusRequest_StatusEnum_name = map[int32]string{
		0: "DRAFT",
		1: "IN_PROCESS",
		2: "COMPLETE",
		3: "CANCEL",
	}
	OrderUpdateStatusRequest_StatusEnum_value = map[string]int32{
		"DRAFT":      0,
		"IN_PROCESS": 1,
		"COMPLETE":   2,
		"CANCEL":     3,
	}
)

func (x OrderUpdateStatusRequest_StatusEnum) Enum() *OrderUpdateStatusRequest_StatusEnum {
	p := new(OrderUpdateStatusRequest_StatusEnum)
	*p = x
	return p
}

func (x OrderUpdateStatusRequest_StatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderUpdateStatusRequest_StatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_order_rpc_order_update_status_proto_enumTypes[0].Descriptor()
}

func (OrderUpdateStatusRequest_StatusEnum) Type() protoreflect.EnumType {
	return &file_rpc_order_rpc_order_update_status_proto_enumTypes[0]
}

func (x OrderUpdateStatusRequest_StatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderUpdateStatusRequest_StatusEnum.Descriptor instead.
func (OrderUpdateStatusRequest_StatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_rpc_order_rpc_order_update_status_proto_rawDescGZIP(), []int{0, 0}
}

type OrderUpdateStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32                               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code OrderUpdateStatusRequest_StatusEnum `protobuf:"varint,2,opt,name=code,proto3,enum=pb.OrderUpdateStatusRequest_StatusEnum" json:"code,omitempty"`
}

func (x *OrderUpdateStatusRequest) Reset() {
	*x = OrderUpdateStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_order_rpc_order_update_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateStatusRequest) ProtoMessage() {}

func (x *OrderUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_order_rpc_order_update_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*OrderUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_order_rpc_order_update_status_proto_rawDescGZIP(), []int{0}
}

func (x *OrderUpdateStatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderUpdateStatusRequest) GetCode() OrderUpdateStatusRequest_StatusEnum {
	if x != nil {
		return x.Code
	}
	return OrderUpdateStatusRequest_DRAFT
}

type OrderUpdateStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OrderUpdateStatusResponse) Reset() {
	*x = OrderUpdateStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_order_rpc_order_update_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateStatusResponse) ProtoMessage() {}

func (x *OrderUpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_order_rpc_order_update_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*OrderUpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_order_rpc_order_update_status_proto_rawDescGZIP(), []int{1}
}

func (x *OrderUpdateStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderUpdateStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_order_rpc_order_update_status_proto protoreflect.FileDescriptor

var file_rpc_order_rpc_order_update_status_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x14, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d,
	0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x18, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x52, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27,
	0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x42, 0x15, 0x92, 0x41, 0x12, 0x32, 0x10, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x20, 0x65, 0x6e, 0x75, 0x6d, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x41, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e,
	0x75, 0x6d, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x00, 0x12, 0x0e, 0x0a,
	0x0a, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43,
	0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x03, 0x22, 0x49, 0x0a, 0x19, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x48, 0x6f, 0x61, 0x6e, 0x67, 0x4c, 0x6f, 0x6e, 0x67, 0x32, 0x35, 0x30, 0x32, 0x2f, 0x70,
	0x68, 0x61, 0x72, 0x6d, 0x61, 0x67, 0x6f, 0x5f, 0x62, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_order_rpc_order_update_status_proto_rawDescOnce sync.Once
	file_rpc_order_rpc_order_update_status_proto_rawDescData = file_rpc_order_rpc_order_update_status_proto_rawDesc
)

func file_rpc_order_rpc_order_update_status_proto_rawDescGZIP() []byte {
	file_rpc_order_rpc_order_update_status_proto_rawDescOnce.Do(func() {
		file_rpc_order_rpc_order_update_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_order_rpc_order_update_status_proto_rawDescData)
	})
	return file_rpc_order_rpc_order_update_status_proto_rawDescData
}

var file_rpc_order_rpc_order_update_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_order_rpc_order_update_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_order_rpc_order_update_status_proto_goTypes = []interface{}{
	(OrderUpdateStatusRequest_StatusEnum)(0), // 0: pb.OrderUpdateStatusRequest.StatusEnum
	(*OrderUpdateStatusRequest)(nil),         // 1: pb.OrderUpdateStatusRequest
	(*OrderUpdateStatusResponse)(nil),        // 2: pb.OrderUpdateStatusResponse
}
var file_rpc_order_rpc_order_update_status_proto_depIdxs = []int32{
	0, // 0: pb.OrderUpdateStatusRequest.code:type_name -> pb.OrderUpdateStatusRequest.StatusEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_order_rpc_order_update_status_proto_init() }
func file_rpc_order_rpc_order_update_status_proto_init() {
	if File_rpc_order_rpc_order_update_status_proto != nil {
		return
	}
	file_entities_order_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_order_rpc_order_update_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdateStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_order_rpc_order_update_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdateStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_order_rpc_order_update_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_order_rpc_order_update_status_proto_goTypes,
		DependencyIndexes: file_rpc_order_rpc_order_update_status_proto_depIdxs,
		EnumInfos:         file_rpc_order_rpc_order_update_status_proto_enumTypes,
		MessageInfos:      file_rpc_order_rpc_order_update_status_proto_msgTypes,
	}.Build()
	File_rpc_order_rpc_order_update_status_proto = out.File
	file_rpc_order_rpc_order_update_status_proto_rawDesc = nil
	file_rpc_order_rpc_order_update_status_proto_goTypes = nil
	file_rpc_order_rpc_order_update_status_proto_depIdxs = nil
}
