// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: rpc/customer/rpc_customer_detail.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomerDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CustomerDetailRequest) Reset() {
	*x = CustomerDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_customer_rpc_customer_detail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerDetailRequest) ProtoMessage() {}

func (x *CustomerDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_customer_rpc_customer_detail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerDetailRequest.ProtoReflect.Descriptor instead.
func (*CustomerDetailRequest) Descriptor() ([]byte, []int) {
	return file_rpc_customer_rpc_customer_detail_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerDetailRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CustomerDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details *CustomerDetail `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *CustomerDetailResponse) Reset() {
	*x = CustomerDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_customer_rpc_customer_detail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerDetailResponse) ProtoMessage() {}

func (x *CustomerDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_customer_rpc_customer_detail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerDetailResponse.ProtoReflect.Descriptor instead.
func (*CustomerDetailResponse) Descriptor() ([]byte, []int) {
	return file_rpc_customer_rpc_customer_detail_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerDetailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CustomerDetailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CustomerDetailResponse) GetDetails() *CustomerDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_rpc_customer_rpc_customer_detail_proto protoreflect.FileDescriptor

var file_rpc_customer_rpc_customer_detail_proto_rawDesc = []byte{
	0x0a, 0x26, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2f, 0x72,
	0x70, 0x63, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70,
	0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x74, 0x0a, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x07, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x61, 0x6e, 0x67, 0x4c, 0x6f, 0x6e, 0x67, 0x32, 0x35, 0x30,
	0x32, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x67, 0x6f, 0x5f, 0x62, 0x65, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_customer_rpc_customer_detail_proto_rawDescOnce sync.Once
	file_rpc_customer_rpc_customer_detail_proto_rawDescData = file_rpc_customer_rpc_customer_detail_proto_rawDesc
)

func file_rpc_customer_rpc_customer_detail_proto_rawDescGZIP() []byte {
	file_rpc_customer_rpc_customer_detail_proto_rawDescOnce.Do(func() {
		file_rpc_customer_rpc_customer_detail_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_customer_rpc_customer_detail_proto_rawDescData)
	})
	return file_rpc_customer_rpc_customer_detail_proto_rawDescData
}

var file_rpc_customer_rpc_customer_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_customer_rpc_customer_detail_proto_goTypes = []interface{}{
	(*CustomerDetailRequest)(nil),  // 0: pb.CustomerDetailRequest
	(*CustomerDetailResponse)(nil), // 1: pb.CustomerDetailResponse
	(*CustomerDetail)(nil),         // 2: pb.CustomerDetail
}
var file_rpc_customer_rpc_customer_detail_proto_depIdxs = []int32{
	2, // 0: pb.CustomerDetailResponse.details:type_name -> pb.CustomerDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_customer_rpc_customer_detail_proto_init() }
func file_rpc_customer_rpc_customer_detail_proto_init() {
	if File_rpc_customer_rpc_customer_detail_proto != nil {
		return
	}
	file_entities_customer_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_customer_rpc_customer_detail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_customer_rpc_customer_detail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_customer_rpc_customer_detail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_customer_rpc_customer_detail_proto_goTypes,
		DependencyIndexes: file_rpc_customer_rpc_customer_detail_proto_depIdxs,
		MessageInfos:      file_rpc_customer_rpc_customer_detail_proto_msgTypes,
	}.Build()
	File_rpc_customer_rpc_customer_detail_proto = out.File
	file_rpc_customer_rpc_customer_detail_proto_rawDesc = nil
	file_rpc_customer_rpc_customer_detail_proto_goTypes = nil
	file_rpc_customer_rpc_customer_detail_proto_depIdxs = nil
}
