Project pharmago {
  database_type: 'PostgresQL'
  Note: '''
    # Pharmago Database
  '''
}

enum gender {
  "nam"
  "nữ"
  "khác"
}

Table accounts as A {
  id serial [pk]
  username varchar [unique, not null]
  hashed_password varchar [not null]
  full_name varchar [not null]
  email varchar [unique, not null]
  type serial [not null]
  is_verify boolean [not null, default: false]
  role serial
  gender gender
  licence varchar
  dob timestamp
  address serial
  password_changed_at timestamptz [not null, default: '0001-01-01 00:00:00Z']
  created_at timestamptz [not null, default: `now()`]
}

Ref: A.type > account_type.id [delete: cascade]
Ref: A.role > roles.id [delete: set null]
Ref: A.address > address.id [delete: set null]

Table account_media {
  id serial [pk]
  account serial [not null]
  media serial [not null]
}

Ref: account_media.account > A.id [delete: cascade]
Ref: account_media.media > medias.id [delete: cascade]

Table account_company {
  id serial [pk]
  account serial [not null]
  company serial [not null]
}

Ref: account_company.account > A.id [delete: cascade]
Ref: account_company.company > C.id [delete: cascade]

Table account_type {
  id serial [pk]
  code varchar [not null]
  title varchar [not null]
}

Table roles as R {
  id serial [pk]
  code varchar [not null]
  title varchar [not null]
  note varchar
  company serial
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Ref: R.company > C.id [delete: cascade]

Table role_item {
  id serial [pk]
  roles serial [not null]
  app varchar [not null]
  value bool [default: false]

  Indexes {
    (roles, app) [unique]
  }
}

Ref: role_item.roles > R.id [delete: cascade]
Ref: role_item.app > apps.code [delete: cascade]

Table apps {
  id serial [pk]
  title varchar [not null]
  code varchar [not null]
  parent varchar
  level int [default: 1]
}

Table sessions {
  id uuid [pk]
  username varchar [not null]
  refresh_token varchar [not null]
  user_agent varchar [not null]
  client_ip varchar [not null]
  is_blocked boolean [not null, default: false]
  expires_at timestamptz [not null]
  created_at timestamptz [not null, default: `now()`]
}

Ref: sessions.username > A.username [delete: cascade]

Table verifies {
  id serial [pk]
  username varchar [not null]
  email varchar [not null]
  secret_code varchar [not null]
  is_used bool [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  expired_at timestamptz [not null, default: `(now() + interval '15 minutes')`]
}

Ref: verifies.username > A.username [delete: cascade]

Table companies as C {
  id serial [pk]
  name varchar [not null]
  code varchar [unique, not null]
  tax_code varchar
  phone varchar
  description varchar
  address serial
  oa_id varchar
  time_open time
  time_close time
  created_at timestamptz [not null, default: `now()`]
  owner serial [ref: > A.id, not null]
  type varchar [not null]
}

Ref: C.address > address.id [delete: set null]
Ref: C.type > company_type.code [delete: set null]

Table company_type {
  code varchar [pk, unique, not null,
    note: '''
    💸 1 = CLINIC, 
    ✔️ 2 = DRUGSTORE
    ''']
  title varchar [unique, not null]
}

Table address {
  id serial [pk]
  lat float [not null]
  lng float [not null]
  province varchar [ref: > provinces.code]
  district varchar [ref: > districts.code]
  ward varchar [ref: > wards.code]
  title varchar [not null]
  user_created serial [ref: > A.id, not null]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    province
    district
    ward
  }
}

Table administrative_regions {
  id serial [pk]
  name varchar [not null]
  name_en varchar [not null]
  code_name varchar [not null]
  code_name_en varchar [not null]
}

Table administrative_units {
  id serial [pk]
  full_name varchar [not null]
  full_name_en varchar [not null]
  short_name varchar [not null]
  short_name_en varchar [not null]
  code_name varchar [not null]
  code_name_en varchar [not null]
}

Table provinces {
  code varchar(20) [pk, unique]
  name varchar [not null]
  name_en varchar [not null]
  full_name varchar [not null]
  full_name_en varchar [not null]
  code_name varchar [not null]
  administrative_unit_id serial [ref: > administrative_units.id]
  administrative_region_id serial [ref: > administrative_regions.id]

  Indexes {
    administrative_unit_id
    administrative_region_id
  }
}

Table districts {
  code varchar [pk, unique]
  name varchar [not null]
  name_en varchar [not null]
  full_name varchar [not null]
  full_name_en varchar [not null]
  code_name varchar [not null]
  province_code varchar [ref: > provinces.code]
  administrative_unit_id serial [ref: > administrative_units.id]

  Indexes {
    province_code
    administrative_unit_id
  }
}

Table wards {
  code varchar [pk, unique]
  name varchar [not null]
  name_en varchar [not null]
  full_name varchar [not null]
  full_name_en varchar [not null]
  code_name varchar [not null]
  district_code varchar [ref: > districts.code]
  administrative_unit_id serial [ref: > administrative_units.id]

  Indexes {
    district_code
    administrative_unit_id
  }
}

Table products as P {
  id serial [pk]
  name varchar [not null]
  code varchar [not null]
  product_category serial
  type serial
  brand serial [not null]
  unit serial [not null]
  ta_duoc varchar(255)
  nong_do varchar(255)
  lieu_dung varchar(255) [not null]
  chi_dinh varchar(255) [not null]
  chong_chi_dinh varchar(255)
  cong_dung varchar(255) [not null]
  tac_dung_phu varchar(255) [not null]
  than_trong varchar(255) [not null]
  tuong_tac varchar(255)
  bao_quan varchar(255) [not null]
  dong_goi varchar(255) [not null]
  phan_loai varchar [default: null]
  dang_bao_che varchar [not null]
  tieu_chuan_sx varchar [not null]
  cong_ty_sx serial [not null]
  cong_ty_dk serial [not null]
  active boolean [not null, default: true]
  company serial [not null]
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    unit
    (id, unit)
  }
}

Ref: P.product_category > product_categories.id [delete: set null]
Ref: P.type > product_type.id [delete: set null]
Ref: P.brand > product_brand.id [delete: cascade]
Ref: U.id - P.unit [delete: cascade]
Ref: P.phan_loai > classify.code [delete: set null]
Ref: P.dang_bao_che > preparation_type.code [delete: cascade]
Ref: P.tieu_chuan_sx > production_standard.code [delete: cascade]
Ref: P.cong_ty_sx > company_pharma.id [delete: cascade]
Ref: P.cong_ty_dk > company_pharma.id [delete: cascade]
Ref: P.company > C.id [delete: cascade]
Ref: P.user_created > A.id [delete: cascade]
Ref: P.user_updated > A.id [delete: set null]

Table products_bank {
  id serial [pk]
  name varchar [not null]
  code varchar [not null]
  ta_duoc varchar(255)
  nong_do varchar(255)
  lieu_dung varchar(255) [not null]
  chi_dinh varchar(255) [not null]
  chong_chi_dinh varchar(255)
  cong_dung varchar(255) [not null]
  tac_dung_phu varchar(255) [not null]
  than_trong varchar(255) [not null]
  tuong_tac varchar(255)
  bao_quan varchar(255) [not null]
  dong_goi varchar(255) [not null]
  phan_loai varchar [default: null]
  dang_bao_che varchar [not null]
  tieu_chuan_sx varchar [not null]
  cong_ty_sx serial [not null]
  cong_ty_dk serial [not null]
}

Ref: products_bank.phan_loai > classify.code [delete: set null]
Ref: products_bank.dang_bao_che > preparation_type.code [delete: cascade]
Ref: products_bank.tieu_chuan_sx > production_standard.code [delete: cascade]
Ref: products_bank.cong_ty_sx > company_pharma.id [delete: cascade]
Ref: products_bank.cong_ty_dk > company_pharma.id [delete: cascade]

Table price_list as PL {
  id serial [pk]
  variant_code varchar [not null, unique]
  variant_name varchar [not null]
  price_import float [not null]
  price_sell float [not null]
  unit serial [not null]
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Ref: PL.variant_code > V.code [delete: cascade]
Ref: PL.unit > U.id [delete: cascade]
Ref: PL.user_created > A.id [delete: cascade]
Ref: PL.user_updated > A.id [delete: set null]

Table price_list_log as PLL {
  id serial [pk]
  old_price_import float [not null]
  new_price_import float [not null]
  old_price_sell float [not null]
  new_price_sell float [not null]
  price_list serial [not null]
  user_updated serial
  updated_at timestamptz [not null, default: `now()`]
}

Ref: PLL.price_list > PL.id [delete: cascade]
Ref: PLL.user_updated > A.id [delete: set null]

Table company_pharma {
  id serial [pk]
  name varchar(255) [not null]
  code varchar(255)
  country varchar(255)
  address varchar(255)
  company_pharma_type varchar [default: null]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    company_pharma_type
    (name, company_pharma_type) [unique]
  }
}

Ref: company_pharma_type.code - company_pharma.company_pharma_type [delete: set null]

Table company_pharma_type {
  id serial [pk]
  code varchar [not null, unique]
  title varchar(255) [not null]
}

Table product_media {
  id serial [pk]
  product serial [not null]
  media serial [not null]

  Indexes {
    product
    media
    (product, media) [unique]
  }
}

Ref: product_media.product > P.id [delete: cascade]
Ref: product_media.media > M.id [delete: cascade]

Table product_categories {
  id serial [pk]
  code varchar [not null, unique]
  name varchar [not null]
  user_created serial [ref: > A.id, not null]
  created_at timestamptz [not null, default: `now()`]
  company serial [not null]
}

Ref: product_categories.company > C.id [delete: cascade]

Table product_brand {
  id serial [pk]
  code varchar [not null, unique]
  name varchar [not null]
  user_created serial [ref: > A.id, not null]
  created_at timestamptz [not null, default: `now()`]
  company serial [not null]
}

Ref: product_brand.company > C.id [delete: cascade]

Table product_type {
  id serial [pk]
  code varchar [not null, unique]
  name varchar [not null]
  user_created serial [ref: > A.id, not null]
  created_at timestamptz [not null, default: `now()`]
  company serial [not null]
}

Ref: product_type.company > C.id [delete: cascade]

Table classify {
  id serial [pk]
  code varchar [not null, unique]
  name varchar [not null, unique]
}

Table preparation_type {
  id serial [pk]
  code varchar [not null, unique]
  name varchar [not null, unique]
}

Table production_standard {
  id serial [pk]
  code varchar [not null, unique]
  name varchar [not null, unique]
}

Table ingredient {
  id serial [pk]
  name varchar [not null]
  weight float [not null, default: 0]
  unit varchar [not null]
  product serial [not null]
}

Ref: ingredient.product > P.id [delete: cascade]

Table units as U {
  id serial [pk]
  name varchar [not null]
  sell_price float [not null, default: 0]
  import_price float [not null, default: 0]
  weight float
  weight_unit varchar
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Ref: U.user_created > A.id [delete: cascade]
Ref: U.user_updated > A.id [delete: set null]

Table unit_changes {
  id serial [pk]
  name varchar [not null]
  value bigint [not null, default: 0]
  sell_price float [not null, default: 0]
  unit serial [not null]
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Ref: unit_changes.unit > U.id [delete: cascade]
Ref: unit_changes.user_created > A.id [delete: cascade]
Ref: unit_changes.user_updated > A.id [delete: set null]

Table variants as V {
  id serial [pk]
  name varchar [not null]
  code varchar [not null, unique]
  barcode varchar [not null]
  decision_number varchar(255) [not null, unique]
  register_number varchar(255) [not null, unique]
  longevity varchar(255) [not null]
  vat float [not null, default: 0]
  product serial [not null]
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Ref: V.product > P.id [delete: cascade]
Ref: V.user_created > A.id [delete: cascade]
Ref: V.user_updated > A.id [delete: set null]

Table variant_media {
  id serial [pk]
  variant serial [not null]
  media serial [not null]

  Indexes {
    variant
    media
    (variant, media) [unique]
  }
}

Ref: variant_media.variant > V.id [delete: cascade]
Ref: variant_media.media > M.id [delete: cascade]

Table promotions {
  id uuid [pk]
  code varchar [unique, not null]
  type varchar
  title varchar
  conditions_text varchar
  conditions_point_customer int
  min_value float [default: 0]
  is_discount_percent bool [default: false, not null] 
  value_discount float [default: 0, not null]
  max_discount float [default: 0]
  time_apply int [note: "null: vố số, int: số lần cụ thể"]
  date_start timestamp
  date_end timestamp
  apply_multiple_times bool [default: false, not null]
  apply_simultaneously bool [default: false, not null]
  status bool [note: "true: áp dụng, false: vô hiệu", not null]
  company serial
  user_created serial [not null]
  user_updated serial
  created_at timestamp [not null, default: `now()`]
  updated_at timestamptz
}

Ref: promotions.user_created > A.id [delete: cascade]
Ref: promotions.company > C.id [delete: set null]
Ref: promotions.user_updated > A.id [delete: set null]
Ref: promotions.type > promotion_type.code [delete: set null]

Table promotion_item {
  id uuid [pk]
  min_buy int [default: 0]
  amount_gift int [default: 0]
  promotions uuid [not null]
  applicable_variant serial
  applicable_service serial
  variant serial
  service serial
}

Ref: promotion_item.promotions > promotions.id [delete: cascade]
Ref: promotion_item.variant > variants.id [delete: set null]
Ref: promotion_item.service > services.id [delete: set null]
Ref: promotion_item.applicable_variant > variants.id [delete: set null]
Ref: promotion_item.applicable_service > services.id [delete: set null]

Table promotion_type {
  code varchar [pk]
  title varchar [note: "1: khuyến mãi giảm giá, 2: khuyến mãi tặng sp"]
}

Table orders as O {
  id serial [pk]
  code varchar(255) [not null, unique]
  total_price float [not null, default: 0]
  description varchar(255)
  vat float [not null, default: 0]
  discount varchar(255) [not null, default: '0']
  service_price float [not null, default: 0]
  must_paid float [not null, default: 0]
  customer serial
  address serial
  status varchar
  type varchar
  ticket serial
  qr serial
  company serial [not null]
  payment serial [not null]
  user_created serial
  user_updated serial
  created_at timestamptz [not null, default: `now()`]
  updated_at timestamptz

  Indexes {
    qr
    (id, qr)
  }
}

Ref: O.customer > customers.id [delete: set null]
Ref: O.status > order_status.code [delete: set null]
Ref: O.type > order_type.code [delete: set null]
Ref: O.ticket > T.id [delete: set null]
Ref: M.id - O.qr [delete: set null]
Ref: O.company > C.id [delete: cascade]
Ref: O.user_created > A.id [delete: set null]
Ref: O.user_updated > A.id [delete: set null]
Ref: payments.id - O.payment [delete: cascade]
Ref: O.address > address.id [delete: set null]

Table order_type {
  id serial [pk]
  code varchar [not null, unique]
  title varchar [not null]
}

Table order_status {
  id serial [pk]
  code varchar [not null, unique]
  title varchar [not null]
}

Table order_items {
  id serial [pk]
  order serial [not null]
  variant serial [not null]
  value int [not null, default: 0]
  total_price float [not null, default: 0]
  consignment serial [note: "Không truyền lúc tạo tự chọn theo BE"]
  consignment_log serial
}

Ref: order_items.order > O.id [delete: cascade]
Ref: order_items.variant > V.id [delete: cascade]
Ref: order_items.consignment > consignment.id [delete: set null]
Ref: order_items.consignment_log > consignment_log.id [delete: set null]

Table service_order_item {
  id serial [pk]
  order serial [not null]
  service serial
  unit_price float [not null, default: 0]
  discount float [not null, default: 0]
  total_price float [not null, default: 0]
}

Ref: service_order_item.order > O.id [delete: cascade]
Ref: service_order_item.service > services.id [delete: set null]

Table customers {
  id serial [pk]
  full_name varchar [not null]
  code varchar [not null]
  company serial [not null]
  address serial
  email varchar
  title varchar [note: "Chức danh"]
  phone varchar(20)
  gender gender
  license varchar(20)
  license_date timestamp
  birthday timestamptz
  group serial
  contact_name varchar
  contact_title varchar
  contact_phone varchar
  contact_email varchar
  contact_address serial
  account_number varchar
  bank_name varchar
  bank_branch varchar
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    address
    (id, address) [unique]
  }
}

Ref: customers.company > C.id [delete: cascade]
Ref: customers.address > address.id [delete: set null]
Ref: customers.contact_address > address.id [delete: set null]
Ref: customers.user_created > A.id [delete: cascade]
Ref: customers.user_updated > A.id [delete: set null]
Ref: customers.group > customer_group.id [delete: set null]

Table customer_group {
  id serial [pk]
  code varchar [not null, unique]
  name varchar [not null]
  company serial [not null]
  note varchar
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Ref: customer_group.company > C.id [delete: cascade]
Ref: customer_group.user_created > A.id [delete: cascade]
Ref: customer_group.user_updated > A.id [delete: set null]

Table medical_records {
  id serial [pk]
  code varchar [not null, unique]
  customer serial [not null]
  weight float
  long float
  symptom varchar [not null, note: 'Triệu chứng']
  diagnostic varchar [not null, note: 'Chuẩn đoán']
  result varchar [not null, note: 'Kết luận']
  doctor serial
  re_examination int [not null, default: 0]
  note varchar
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp
  user_created serial
  user_updated serial
}

Ref: medical_records.customer > customers.id [delete: set null]
Ref: medical_records.doctor > A.id [delete: set null]
Ref: medical_records.user_created > A.id [delete: set null]
Ref: medical_records.user_updated > A.id [delete: set null]

Table medical_record_variant {
  id serial [pk]
  medical_record serial [not null]
  variant serial [not null]
}
Ref: medical_record_variant.medical_record > medical_records.id [delete: set null]
Ref: medical_record_variant.variant > V.id [delete: set null]

Table payment_item_types {
  id serial [pk]
  code varchar(255) [not null, unique]
  title varchar(255) [not null]
}

Table payments {
  id serial [pk]
  code varchar [not null, unique]
  must_paid float [not null, default: 0]
  had_paid float [not null, default: 0]
  need_pay float [not null, default: 0]
}

Table payment_items {
  id serial [pk]
  type varchar [not null]
  value float [not null, default: 0]
  is_paid bool [not null, default: false]
  payment serial [not null]
  extra_note varchar
}

Ref: payment_items.type > payment_item_types.code [delete: cascade]
Ref: payment_items.payment > payments.id [delete: cascade]

Table medias as M {
  id serial [pk]
  media_url varchar [not null]
}

Table warehouses as W {
  id serial [pk]
  name varchar(255) [not null]
  code varchar(255) [not null, unique]
  address serial
  companies serial
}

Ref: W.address > address.id [delete: set null]
Ref: W.companies > C.id [delete: cascade]

Table tickets as T {
  id serial [pk]
  code varchar [not null]
  type serial
  status serial
  note varchar
  qr serial
  export_to serial
  import_from serial
  total_price float [not null, default: 0]
  warehouse serial [not null]
  user_created serial [not null]
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    qr
    (id, qr) [unique]
  }
}

Ref: T.type > ticket_type.id [delete: set null]
Ref: T.status > ticket_status.id [delete: set null]
Ref: M.id - T.qr [delete: set null]
Ref: T.export_to > address.id [delete: set null]
Ref: T.import_from > address.id [delete: set null]
Ref: T.warehouse > W.id [delete: cascade]
Ref: T.user_created > A.id [delete: cascade]
Ref: T.user_updated > A.id [delete: set null]

Table ticket_type {
  id serial [pk]
  code varchar [not null]
  title varchar [not null]
}

Table ticket_status {
  id serial [pk]
  code varchar [not null]
  title varchar [not null]
}


Table consignment {
  id serial [pk]
  code varchar [not null, unique]
  quantity int [not null, default: 0]
  inventory int [not null, default: 0]
  ticket serial
  variant serial
  expired_at timestamptz [not null]
  producted_at timestamptz [not null]
  is_available bool [not null, default: false]
  user_created serial
  user_updated serial
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Ref: consignment.ticket > T.id [delete: cascade]
Ref: consignment.variant > V.id [delete: cascade]
Ref: consignment.user_created > A.id [delete: set null]
Ref: consignment.user_updated > A.id [delete: set null]

Table consignment_log {
  id serial [pk]
  consignment serial [not null]
  inventory int [not null, default: 0]
  amount_change int [not null, default: 0]
  user_created serial
  created_at timestamptz [not null, default: `now()`]
}

Ref: consignment_log.consignment > consignment.id [delete: cascade]
Ref: consignment_log.user_created > A.id [delete: set null]

Table suplier {
  id serial [pk]
  code varchar [not null, unique]
  name varchar(255) [not null]
  deputy_name varchar(255) [not null]
  phone varchar(255) [not null]
  email varchar(255)
  address serial
  warehouses serial
  company serial
}

Ref: suplier.warehouses > warehouses.id [delete: set null]
Ref: suplier.address > address.id [delete: set null]
Ref: suplier.company > C.id [delete: cascade]

Table debt_note_type {
  code varchar [pk, unique]
  title varchar
}

Table debt_note_status {
  code varchar [pk, unique]
  title varchar
}

Table debt_note {
  id serial [pk]
  code varchar [not null, unique]
  title varchar
  entity varchar [not null]
  money float [not null, default: 0]
  paymented float [not null, default: 0]
  note varchar
  type varchar [not null]
  status varchar [not null]
  company serial [not null]
  user_created serial [not null]
  exprise timestamp [not null]
  dabt_note_at timestamp [default: `now()`]
}

Ref: debt_note.type > debt_note_type.code [delete: set null]
Ref: debt_note.status > debt_note_status.code [delete: set null]
Ref: debt_note.user_created > A.id [delete: set null]
Ref: debt_note.company > C.id [delete: set null]

Table debt_repayment {
  id serial [pk]
  code varchar [unique, not null]
  money float [not null, default: 0]
  created_at timestamp [default: `now()`]
  debt serial [not null]
  user_created serial [not null]

  Indexes {
    (debt, money)
  }
}

Ref: debt_repayment.user_created > A.id [delete: set null]
Ref: debt_repayment.debt > debt_note.id [delete: set null]

Table services {
  id serial [pk]
  active bool [not null, default: true]
  image serial
  code varchar [not null, unique]
  title varchar [not null]
  entity varchar
  staff serial [not null]
  frequency varchar
  reminder_time int [note: 'Thời gian nhắc hẹn (seconds)']
  unit varchar [not null]
  price float [not null, default: 0]
  description varchar
  company serial [not null]
  user_created serial [not null]
  user_updated serial
  created_at timestamp [not null, default: `now()`]
  updated_at timestamp
}

Ref: services.staff > A.id
Ref: services.company > C.id
Ref: M.id - services.image
Ref: services.user_created > A.id
Ref: services.user_updated > A.id

Table service_variant {
  id serial [pk]
  service serial
  variant serial

  Indexes {
    (service, variant) [unique]
  }
}

Ref: service_variant.service > services.id [delete: cascade]
Ref: service_variant.variant > V.id

Table notification as N {
  id serial [pk]
  type varchar [not null]
  topic varchar [not null]
  title varchar [not null]
  content varchar [not null]
  is_read bool [not null, default: false]
  data varchar [note: 'save code entity']
  company serial
  created_at timestamp [not null, default: `now()`]
}

Ref: N.type > noti_type.code [delete: set null]
Ref: N.company > C.id [delete: set null]

Table noti_type {
  code varchar [unique, not null]
}

Table appointment_schedules as AS {
  id serial [pk]
  uuid uuid [unique, not null]
  code varchar [unique, not null]
  customer serial
  company serial
  doctor serial
  symptoms varchar [note: "Triệu chứng bệnh"]
  diagnostic varchar [note: "Chuẩn đoán bệnh"]
  qr_code_url varchar
  is_done bool [note: "true: Đã xong, false: Chưa diễn ra", not null]
  meeting_at timestamp [not null]
  user_created serial [not null]
  user_updated serial
  created_at timestamp [not null, default: `now()`]
  updated_at timestamptz
}

Ref: AS.customer > customers.id [delete: set null]
Ref: AS.company > C.id [delete: set null]
Ref: AS.doctor > A.id [delete: set null]
Ref: AS.user_created > A.id
Ref: AS.user_updated > A.id [delete: set null]

Table appointment_schedule_service as ASS {
  id serial [pk]
  as_uuid uuid [not null]
  service serial
  order_service serial
}

Ref: ASS.as_uuid > AS.uuid
Ref: ASS.service > services.id [delete: set null]
Ref: ASS.order_service > orders.id [delete: set null]

Table appointment_schedule_url as ASU {
  id serial [pk]
  as_uuid uuid [not null]
  url varchar
  name_doc varchar
}

Ref: ASU.as_uuid > AS.uuid

Table appointment_schedule_drug as ASD {
  id serial [pk]
  as_uuid uuid [not null]
  variant serial
  lieu_dung varchar
  quantity int [not null, default: 0]
}

Ref: ASD.as_uuid > AS.uuid
Ref: ASD.variant > variants.id [delete: set null]

enum medical_record_link_type {
  test
  patient
  diagnostic
}

Table medical_record_link as MRL {
  id serial [pk]
  uuid uuid [not null]
  type medical_record_type [not null]
  title varchar
  url varchar [not null]
  customer serial
  appointment_schedule uuid
  user_created serial
  created_at timestamp [not null, default: `now()`]
}

Ref: MRL.customer > customers.id [delete: cascade]
Ref: MRL.appointment_schedule > appointment_schedules.uuid [delete: set null]
Ref: MRL.user_created > A.id [delete: set null]