Project pharmago {
  database_type: 'PostgresQL'
  Note: '''
    # Pharmago Database
  '''
}

Table accounts as A {
  id bigserial [pk]
  username varchar [unique, not null]
  hashed_password varchar [not null]
  full_name varchar [not null]
  email varchar [unique, not null]
  type bigserial [ref: > account_type.code, not null]
  is_verify boolean [not null, default: false]
  password_changed_at timestamptz [not null, default: '0001-01-01 00:00:00Z']
  created_at timestamptz [not null, default: `now()`]
}

Table account_media {
  id bigserial [pk]
  account bigserial [ref: > A.id, not null]
  media bigserial [ref: > medias.id, not null]
}

Table account_company {
  id bigserial [pk]
  account bigserial [ref: > A.id, not null]
  company bigserial [ref: > C.id, not null]
}

Table account_type {
  id bigserial [pk]
  code varchar [not null]
  title varchar [not null]
}

Table sessions {
  id uuid [pk]
  username varchar [ref: > A.username, not null]
  refresh_token varchar [NOT NULL]
  user_agent varchar [NOT NULL]
  client_ip varchar [NOT NULL]
  is_blocked boolean [NOT NULL, default: false]
  expires_at timestamptz [NOT NULL]
  created_at timestamptz [NOT NULL, default: `now()`]
}

Table verifies {
  id bigserial [pk]
  username varchar [ref: > A.username, NOT NULL]
  email varchar [NOT NULL]
  secret_code varchar [NOT NULL]
  is_used bool [NOT NULL, default: false]
  created_at timestamptz [NOT NULL, default: `now()`]
  expired_at timestamptz [NOT NULL, default: `(now() + interval '15 minutes')`]
}

Table companies as C {
  id bigserial [pk]
  name varchar [not null]
  code varchar [unique, not null]
  tax_code varchar
  phone varchar
  description varchar
  address bigserial [ref: > address.id, not null]
  created_at timestamptz [not null, default: `now()`]
  owner bigserial [ref: > A.id, not null]
}

Table address {
  id bigserial [pk]
  lat numeric [not null]
  lng numeric [not null]
  province varchar [ref: > provinces.code]
  district varchar [ref: > districts.code]
  ward varchar [ref: > wards.code]
  title varchar [not null]
  user_created bigserial [ref: > A.id, not null]
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    province
    district
    ward
  }
}

Table administrative_regions {
  id bigserial [pk]
  name varchar [not null]
  name_en varchar [not null]
  code_name varchar [not null]
  code_name_en varchar [not null]
}

Table administrative_units {
  id bigserial [pk]
  full_name varchar [not null]
  full_name_en varchar [not null]
  short_name varchar [not null]
  short_name_en varchar [not null]
  code_name varchar [not null]
  code_name_en varchar [not null]
}

Table provinces {
  code varchar(20) [pk, unique]
  name varchar [not null]
  name_en varchar [not null]
  full_name varchar [not null]
  full_name_en varchar [not null]
  code_name varchar [not null]
  administrative_unit_id bigserial [ref: > administrative_units.id]
  administrative_region_id bigserial [ref: > administrative_regions.id]

  Indexes {
    administrative_unit_id
    administrative_region_id
  }
}

Table districts {
  code varchar [pk, unique]
  name varchar [not null]
  name_en varchar [not null]
  full_name varchar [not null]
  full_name_en varchar [not null]
  code_name varchar [not null]
  province_code varchar [ref: > provinces.code]
  administrative_unit_id bigserial [ref: > administrative_units.id]

  Indexes {
    province_code
    administrative_unit_id
  }
}

Table wards {
  code varchar [pk, unique]
  name varchar [not null]
  name_en varchar [not null]
  full_name varchar [not null]
  full_name_en varchar [not null]
  code_name varchar [not null]
  district_code varchar [ref: > districts.code]
  administrative_unit_id bigserial [ref: > administrative_units.id]

  Indexes {
    district_code
    administrative_unit_id
  }
}

Table warehouses as W {
  id bigserial [pk]
  address bigserial [ref: > address.id, not null]
  companies bigserial [ref: > C.id, not null]

  Indexes {
    address
    (id, address) [unique]
  }
}

Table products as P {
  id bigserial [pk]
  name varchar [not null]
  code varchar [not null]
  product_category bigserial [ref: > product_categories.id]
  type bigserial [ref: > product_type.id]
  unit bigserial [ref: - U.id, not null]
  taDuoc varchar(255)
  nongDo varchar(255)
  lieuDung varchar(255) [not null]
  chiDinh varchar(255) [not null]
  chongChiDinh varchar(255)
  congDung varchar(255) [not null]
  tacDungPhu varchar(255) [not null]
  thanTrong varchar(255) [not null]
  tuongTac varchar(255)
  baoQuan varchar(255) [not null]
  dongGoi varchar(255) [not null]
  noiSx varchar(255) [not null]
  congTySx varchar(255) [not null]
  congTyDk varchar(255) [not null]
  company bigserial [ref: > C.id]
  user_created bigserial [ref: > A.id, not null]
  user_updated bigserial [ref: > A.id]
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    unit
    (id, unit) [unique]
  }
}

Table product_media {
  id bigserial [pk]
  product bigserial [ref: > P.id]
  media bigserial [ref: > M.id]

  Indexes {
    product
    media
    (product, media) [unique]
  }
}

Table product_categories {
  id bigserial [pk]
  name varchar [not null]
  user_created bigserial [ref: > A.id, not null]
  user_updated bigserial [ref: > A.id]
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Table product_type {
  id bigserial [pk]
  name varchar [not null]
}

Table units as U {
  id bigserial [pk]
  name varchar [not null]
  sell_price numeric [not null, default: 0]
  import_price numeric [not null, default: 0]
  weight numeric
  weight_unit varchar
  user_created bigserial [ref: > A.id, not null]
  user_updated bigserial [ref: > A.id]
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Table unit_changes {
  id bigserial [pk]
  name varchar [not null]
  value bigint [not null, default: 0]
  sell_price numeric [not null, default: 0]
  unit bigserial [ref: > U.id]
  user_created bigserial [ref: > A.id, not null]
  user_updated bigserial [ref: > A.id]
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Table variants as V {
  id bigserial [pk]
  name varchar [not null]
  code varchar [not null, unique]
  barcode varchar [not null]
  decision_number varchar(255) [not null, unique]
  register_number varchar(255) [not null, unique]
  longevity varchar(255) [not null]
  vat numeric [not null, default: 0]
  product bigserial [ref: > P.id]
  user_created bigserial [ref: > A.id, not null]
  user_updated bigserial [ref: > A.id]
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]
}

Table variant_media {
  id bigserial [pk]
  variant bigserial [ref: > V.id, not null]
  media bigserial [ref: > M.id, not null]

  Indexes {
    variant
    media
    (variant, media) [unique]
  }
}

Table orders as O {
  id bigserial [pk]
  vat numeric [not null, default: 0]
  total_price numeric [not null, default: 0]
  description varchar
  customer bigserial [ref: > customers.id]
  status bigserial [ref: > order_status.id, not null]
  type bigserial [ref: > order_type.id]
  ticket bigserial [ref: > T.id]
  qr bigserial [ref: > M.id]

  Indexes {
    qr
    (id, qr) [unique]
  }
}

Table order_type {
  id bigserial [pk]
  code varchar [not null]
  title varchar [not null]
}

Table order_status {
  id bigserial [pk]
  code varchar [not null]
  title varchar [not null]
}

Table order_items {
  id bigserial [pk]
  order bigserial [ref: > O.id]
  variant bigserial [ref: > V.id]
  value int [not null, default: 0]
  expired_at timestamptz
  manufactured_at timestamptz
}

Table customers {
  id bigserial [pk]
  full_name varchar [not null]
  code varchar [not null]
  company bigserial [ref: > C.id]
  address bigserial [ref: > address.id]
  email varchar
  birthday timestamptz
  user_created bigserial [ref: > A.id, not null]
  user_updated bigserial [ref: > A.id]
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    address
    (id, address) [unique]
  }
}

Table tickets as T {
  id bigserial [pk]
  code varchar [not null]
  type bigserial [ref: > ticket_type.id, not null]
  status bigserial [ref: > ticket_status.id, not null]
  note varchar
  qr bigserial [ref: > M.id]
  export_from bigserial [ref: > W.id, not null]
  import_to bigserial [ref: > W.id, not null]
  user_created bigserial [ref: > A.id, not null]
  user_updated bigserial [ref: > A.id]
  updated_at timestamptz
  created_at timestamptz [not null, default: `now()`]

  Indexes {
    qr
    (id, qr) [unique]
  }
}


Table ticket_type {
  id bigserial [pk]
  code varchar [not null]
  title varchar [not null]
}

Table ticket_status {
  id bigserial [pk]
  code varchar [not null]
  title varchar [not null]
}

Table medias as M {
  id bigserial [pk]
  media_url varchar [not null]
}









